### ISSUE TITLE
I would like to be able to merge in tab modifier files

### ISSUE THREAD

**Issue by 42degrees** [sylouuu/chrome-tab-modifier#100]
Currently you can save and load modifier files (which saved me at least once already), but to promote sharing of modifier files for web sites that are really bad at creating titles (Amazon AWS is terrible, and I'm working on a complete set that will properly name the AWS tabs) it would be nice to be able to put them out there for others to download and import, but they wouldn't want them to replace the existing set, which is what appears to happen now.

Actually, it probably should be a choice, merge or replace.  Merges with modifiers of the same name should replace previous modifiers with that exact name (not add new ones).  That way if I create a set, and you import it, and then improve it, say with better replacement parameters, merging it in wouldn't duplicate all the rules, but replace them with the improved ones.

**Comment by sylouuu** [comment]
Hi @42degrees,

Sure it could be nice to have the between "erase and add" and "merge". But to keep the merge simple for everyone, it would not check for duplicate rules, just add the file rules without erasing existing one.

The user will have to deal with duplicates himself.

What do you think about this?

Best

**Comment by 42degrees** [comment]
Now that I have the $1 stuff working it makes the actual number of rules that I have to define much fewer.  Initially I thought I was going to have a rule per logical page to get it working.  If I can do a site as big as AWS with only a dozen rules or so, then it might not be a big deal.

Certainly if  there was a merge feature, other tweaks to that feature can wait and see if others complain about it.

**Comment by sylouuu** [comment]
Gonna close this, too specific to work on it. Thanks for contributing again.

Best
