### ISSUE TITLE
Request: Allow matching key to be URL and/or TITLE

### ISSUE THREAD

**Issue by daveysaxt** [sylouuu/chrome-tab-modifier#102]
This is more of a request than an issue, but... If like me you have multiple gmail accounts and want a rule to modify each different gmail account tab separately, because gmail does not put anything to identify your email address in the URL, but uses a generated URL scheme such as mail.google.com/mail/u/1/#inbox, there is no way to 'key' into each of your own different gmail tabs.

Therefore, could the rule 'Key' please be extended to selectably match against TITLE in addition to URL ?

Just a thought.

Cheers,

Dave

**Comment by sylouuu** [comment]
Hi @daveysaxt,

I'm not sure to understand what you want to achieve. Please provide an explicit example.

Best

**Comment by psilver1** [comment]
I had in mind a similar request. I use google drive documents and sheets a lot and have several google sheets tabbed with different colors using the tab modifier. But the issue I am running into is that the URL will change as you edit the google sheet.

Is there any way the tab could link to the first part of the URL that does not change and the title of the tab to verify it?

**Comment by sylouuu** [comment]
@psilver1 You can use "Starts with" that will match the beginning of your URL fragment.

Also with both title matcher & URL matcher you can also match everything if you are familiar with RegExp.

Best

**Comment by daveysaxt** [comment]
Basically, if you go into Gmail, the URL is generated by gmail, so if you have say 3 email accounts and go into all of them, each in a separate tab, as often I do, you get the urls:

https://mail.google.com/mail/u/0/
https://mail.google.com/mail/u/1/
https://mail.google.com/mail/u/2/

and if say you close tab .../u/1 by accident and open a new tab and re-log into that particular gmail, you're likely to get ...u/3

There is nothing in the gmail URL to match the u/0, u/1 or u/2 to say myemail1@gmail.com, dave1mail@gmail.com, rabbitthingymybob@gmail.com. Only the Title of the tab (page) shows, for example "Inbox (6) - rabbitthingymybob@gmail.com", therefore identifying which of your email accounts the tab is displaying. So to create a rule that is triggered for a particular Title pattern rather than or in addition to a particular URL pattern would be needed.

As far as I understand it, the Title matching pattern field (at the bottom of the rule definition) is to match a part of the title and replace it with something else in the tab (page) title ? As is the URL pattern matching field at the bottom ? As far as I have tried, the Title matching pattern is not to identify a particular webpage for applying a rule to ?

What I was suggesting is that if the extension could use Title and/or URL to match against for determining if that rule should be applied to the tab (page)... for example having a different favicon for each of my (several) email accounts.

In summary,  URL pattern matching can't achieve this for dynamically generated URLs of the gmail kind. It is not guaranteed what u/_**n**_/ you will get in the gmail URL for any of your email addresses. There are other websites and services that also use dynamically generated 'session URLS' that are not the same every time a particular user starts such a session, and there is also nothing in the URL to identify the session (except to the server generating the page).

So, basically allowing the rule to be triggered by a pattern match on URL and/or Title. I did try using patterns in the first URL matching field to try and force a match to Title in the hopes that I could bust past the end of the URL and scan along to the title, but I guess the exetension specifically limits the regexp scan to just the URL 'field' ?

Many Thanks,

Dave

**Comment by sylouuu** [comment]
I got it. Yes the tab identification relies only on the URL and I have no plan to actually supports anything else (ref. to the focused scope inside the Readme file).

So yes if you apply a rule on a Gmail account, all will be affected.

Best
