### ISSUE TITLE
Sample Github tab title

### ISSUE THREAD

**Issue by adellhk** [sylouuu/chrome-tab-modifier#103]
Thanks for this extension! Super handy! One suggestion: on the Readme you might like to add this example:

Github final-path as title for blobs:
**Detection:** RegExp
**URL fragment:** github[.]com/([A-Za-z0-9_-]+)/([A-Za-z0-9_-]+)/blob/
**Title:** {.final-path}

**Comment by sylouuu** [comment]
Thanks @adellhk for contributing!

Example added! Best
