### ISSUE TITLE
A Pinned Tab has no name!?

### ISSUE THREAD

**Issue by MasterFuba** [sylouuu/chrome-tab-modifier#106]
### Tab Modifier version

**Browser:** `Chrome`

**Extension version:** `0.20.0`

### Expected behavior

the name of a Tab should not get removed if a tab is pinned.
Pinned tab is nice as it is, but i would also like to rename it. Right now i have only color icons and must remember which color stands for what...

### Actual behavior

name of tab is removed, only very tiny tab with icon is visible anymore

### Steps to reproduce the behavior

1. define a name for specific url to get the tab mopdified (new name)
2. pin that tap
3. look what name the tab has now -> no name anymore

**Comment by sylouuu** [comment]
Hi @MasterFuba,

I'm not sure if the concept of pinned tab is clear for you, a pinned tab hides its title to let more space in the tab bar but the title is not removed. You have to hover the pinned tab with the mouse to see the title as a tooltip.

Tab Modifier does not interfere with this Chrome core feature.

**Comment by ChristianDfind** [comment]
It's clear to me. But I'd like this feature anyway - even to be able to give a pinned tab a name as an option would be great.

**Comment by norrisollie** [comment]
It would be great to have this feature. On Visual Studio Code it pins the tab and keeps the name to....

**Comment by Paxy** [comment]
The most useful pinned tab is the Gmail tab. But if it is pinned without a title, it becomes useless as you don't know is there are any new mails. You should, at least, give the option to show titles on pinned tabs.

**Comment by sylouuu** [comment]
> The most useful pinned tab is the Gmail tab. But if it is pinned without a title, it becomes useless as you don't know is there are any new mails. You should, at least, give the option to show titles on pinned tabs.

You can't control that. Anyway, in the GMail settings, you can show the number of unread messages in the favicon, it works even if it's pinned.

**Comment by Paxy** [comment]
@sylouuu tnx, I didn't know about that. It is "Unread message icon" option in Advanced Gmail settings.
