### ISSUE TITLE
Title shown on pinned tabs.

### ISSUE THREAD

**Issue by balderclaassen** [sylouuu/chrome-tab-modifier#107]
Great extension, thanks ! :+1: 
I love that I can add my own favicon. What I am still missing, from chrome(and ff) and thus also from this extension would be showing the title of a tab, when it is pinned. I don't know if this is something you can add, but that would be awesome, I don't know why browser's think that I don't need titles on pinned tabs.

**Comment by sylouuu** [comment]
Hey @balderclaassen,

This is a Chrome specification.

Ref. https://github.com/sylouuu/chrome-tab-modifier/issues/106

**Comment by balderclaassen** [comment]
Okey good to know, thanks for the ref. 
I personally like pined tabs for remaining across browser sessions and sticking to the left of the tab bar. I don't like small sized tabs, but that's for me to ask chrome to change then :)
