### ISSUE TITLE
change the favicon icon for a local tab such as "chrome://history/"

### ISSUE THREAD

**Issue by YousefMMS** [sylouuu/chrome-tab-modifier#11]

**Comment by sylouuu** [comment]
Hi @YousefMMS,

Unfortunately, it seems that the extension can't access to the `chrome://*` tabs.

Bests

**Comment by ZephireNZ** [comment]
Sorry to dredge up an old issue - is this the case for `chrome-extension://`  URLs as well? Trying to fix IETab using the same icon :stuck_out_tongue:

**Comment by sylouuu** [comment]
Yes @ZephireNZ, same behavior for other extensions.
