### ISSUE TITLE
It Isn't Obvious That Tab Modifier Automatically Launches Tabs In Rules on Chrome Startup

### ISSUE THREAD

**Issue by djbreen7** [sylouuu/chrome-tab-modifier#114]
Just an observation. I was putting all of my tabs in my Chrome "On Startup" section. This caused wonky behavior since both Chrom and Tab Modifier were creating instances of my tabs:

- If my rules were "Unique", tab modifier would occasionally see the duplicates and close both.
- If my rules were NOT Unique, tab modifier would duplicate tabs.

**Comment by djbreen7** [comment]
Looks like this was chrome caching settings. My mistake.

**Comment by sylouuu** [comment]
Rules are applying when a tab is loading. ;)

Best
