### ISSUE TITLE
Bug: Weird behavior when opening links in a unique Facebook Messenger tab in a new tab

### ISSUE THREAD

**Issue by sevrlbats** [sylouuu/chrome-tab-modifier#116]
### Tab Modifier version

**Browser:** Chrome

**Extension version:** 0.21.0

### Expected behavior

(I've filled out the template, but here's a brief video demoing and explaining the behavior as well: https://youtu.be/kBLRTVHBTkw )

When opening a link in Facebook Messenger as a new tab with middle mouse or right-click+open in new tab, I'd expect the link to open it in a new tab.

### Actual behavior

The extension treats it like I've opened a new copy of Facebook and seems to trigger some of the unique tab behavior--the page loads for a second, then the Facebook tab closes and reloads the target page.

### Steps to reproduce the behavior

Trying to open any link in a new tab in Facebook messenger seems to cause the problem for me.

I should note that my Twitter tab is also unique and does not share this same source-tab-munching behavior.

**Comment by sylouuu** [comment]
Hello @sevrlbats,

Thanks for nice reporting. I think you have a rule like "Contains" "facebook.com".

When you click on a link, check the URL in the left bottom corner, you'll see "https://l.facebook.com", thats means TM matches your rule. To avoid this, change your rule as follows: "Starts with" "https://www.facebook.com".

Hope that helps!

**Comment by sevrlbats** [comment]
Heyyy, that was it! I was halfway thinking that a starts with might fix this and then it slipped my mind. Thanks, this is gonna make my life considerably easier!

**Comment by sylouuu** [comment]
Glad it's OK for you!
