### ISSUE TITLE
www.google.com on Chrome shows repeat alert~

### ISSUE THREAD

**Issue by Milo233** [sylouuu/chrome-tab-modifier#117]
Chrome
version 0.21.0
### Steps to reproduce the behavior
I set it as 'Contains', keyword ' google', icon url : https://png.icons8.com/color/50/000000/gas-industry.png

It works well, the icon is changed as I set.

But everytime when I search something in google, it always remind me that ' do u want to leave this page? the change may not be saved. '. By the way, my chrome browser is set to Chinese, I get only chinese message. I just translate it into english for you

So is there a way to avoid the alert when I was searching?

Thanks for your effort on this useful tool!

**Comment by sylouuu** [comment]
Hi,

Disable the "Protected" action in your rule if you don't want this alert.

Best

**Comment by Milo233** [comment]
wow, it works! Thanks a lot!
