### ISSUE TITLE
Cannot change some websites favicons

### ISSUE THREAD

**Issue by Marubozu** [sylouuu/chrome-tab-modifier#119]
Hi, I love this app and I have been using it for quite some time. Can't use my computer without it!!

I have created 50+ rules, most of them to replace website favicons.

However, for some websites, no matter which external URL I use for the new icon, the favicon would not change. For example, I am trying to replace the favicon on https://www.amzcockpit.com/

**Steps to reproduce:**
1. Open the Tab Modifier extension.
2. Click on "Add a new rule".
3. Fill the details:
Name = AMZ
Detection = Contains
URL fragment = amzcockpit
Icon = http://images2.appzoome.com/2017/0730/amazon-seller-430_9f6f2.png
Other options = not modified, default settings remain
4. Save the rule.
5. Open or Refresh the https://www.amzcockpit.com

**Expected behaviour:**
The favicon on https://www.amzcockpit.com is replaced by the picture from the icon URL set on step 3.

**Actual behaviour:**
The favicon remains the same OR randomly displays Chrome default favicon when browsing / refreshing the website (see screenshot).

Surprisingly:
1. The icon I wish to use is fetched properly as it is visible on the page "List of rules" in the Tab Modifier extension (see screenshot).
2. By using internal icons (for example "Blue alt"), the website updates the favicon properly, as expected (see screenshot).

Is there anything I am missing here? Thanks so much for your help!

### Tab Modifier version:  0.21.0

**Browser:** Chrome Version 64.0.3282.140 (Official Build) (64-bit)

**OS:** MacOS 10.13.3

**Extension version:**  0.21.0

**The 3 screenshots:**

<img width="732" alt="screen shot 2018-02-06 at 15 16 06" src="https://user-images.githubusercontent.com/36198887/35868221-d0a36b28-0b53-11e8-802a-48775b1c30bf.png">

<img width="1280" alt="screen shot 2018-02-06 at 15 12 34" src="https://user-images.githubusercontent.com/36198887/35868220-d087edee-0b53-11e8-8cc4-a8938b663d0e.png">

<img width="1280" alt="screen shot 2018-02-06 at 15 31 04" src="https://user-images.githubusercontent.com/36198887/35868222-d0c12c1c-0b53-11e8-82f5-4e6dca7a966a.png">

**Comment by sylouuu** [comment]
Thanks for your feedback. This is related to the domain you use for this image.

The website tries to load each resource with HTTPS, and you have specified "http://...". The website wants to reach this image with the HTTPS but the connection is refused (see Developer Console). So I suggest you to download this image and upload it elsewhere (try the imgur service). Take the direct link with HTTPS it should work.

Bests

**Comment by Marubozu** [comment]
Thank you for such quick answer! I usually upload my own pictures on Pix Toile, which is similar to imgur but not with HTTPS.

Anyway, I have just tried to use the following picture instead, which is as per your advice coming from a HTTPS source:

https://img.podgate.com/img/freeapps/794/1_794141485-icon350x350.jpeg

After refreshing the page several times, the icon has finally been replaced so it now works!
That said, I still have an error in the Console. I have attached the screenshot, just FYI.

Thank you so much for your help! Maybe this specific case could be added to the Help section, in case someone faces the same issue? ;)


<img width="1279" alt="screen shot 2018-02-06 at 16 20 31" src="https://user-images.githubusercontent.com/36198887/35870950-e204d04e-0b5a-11e8-90c9-146ff0cb2e91.png">

**Comment by Marubozu** [comment]
Well, I actually have the issue again with this website. I didn't make any modification since my last message but the icon won't update...

**Comment by sylouuu** [comment]
You can't do much as said before.

This website has added a [CSP](https://en.wikipedia.org/wiki/Content_Security_Policy), that means they have whitelisted few domains. You can't inject anything from a non-whitelisted domain. Otherwise, tell me how did you do.

Best

**Comment by sylouuu** [comment]
Anyway, try the DataURI thing as described [there](https://github.com/sylouuu/chrome-tab-modifier#local-icon-path-doesnt-work).

**Comment by Marubozu** [comment]
The trick with Data URI did work! Thanks so much Syl!

**Comment by sylouuu** [comment]
Awesome! See you!
