### ISSUE TITLE
Tabs being named to the CSS selector

### ISSUE THREAD

**Issue by jetk** [sylouuu/chrome-tab-modifier#121]
Hi, 

I'm hoping this is user error but myself and a few others are struggling to get this extension to work using CSS selectors in the title field. I'm trying to pick up the label of the work item I'm viewing in VSTS, but unless I've misread the instructions putting in CSS selector just renames the tab to the text of that selector.

### Tab Modifier version

**Browser:** `Chrome` 

**Extension version:** `0.21.0`

_Can be found here: chrome://extensions/?id=hcbgadmbdkiilgpifjgcakjehmafcjai_

### Expected behavior

_Chrome tab to be renamed to VSTS work item number, it is a span with an aria label eg <span aria-label="ID Field">37914</span>

### Actual behavior

It renamed the tab to the selectors I tried using

### Steps to reproduce the behavior

_Please describe the steps to help me to reproduce the actual behavior_

1. Create a rule which matches https://_mydomain_.visualstudio.com
2. In the title field, try anything ranging from [aria-label] to [aria-label="ID-Field"]
3. Save rule and Reload the VSTS page

**Comment by jetk** [comment]
So this was actually down to two things:
First of all, syntax when selecting by attribute needs to be {[attr="value"]}, which might be helpful to clarify in the instructions
Second of all, VSTS seems to change its title after initial load so it may take a moment for the DOM to settle, which is why I was seeing the plaintext of the selector for up to 10s (and thus assuming it hadn't worked and trying something else)

**Comment by sylouuu** [comment]
Thanks for your feedback!
