### ISSUE TITLE
Feature Request: Coloured Tabs

### ISSUE THREAD

**Issue by joshua-fogg** [sylouuu/chrome-tab-modifier#125]
I would like to have a more visible way to differentiate tabs. I think  being able to set a Tab or a group of tabs a certain colour. This could be done via URL fragment or by a click perhaps. 

This would make my life a lot easier as tab icons and titles become difficult to read as the tab bar fills up

**Comment by sylouuu** [comment]
Hello,

Unfortunately, Chrome does not support colored tabs.

Bests
