### ISSUE TITLE
Local files that start with file:///

### ISSUE THREAD

**Issue by ndeubert** [sylouuu/chrome-tab-modifier#13]
Hello, Thanks for the extension, it is exactly what I was looking for, but I can't seem to get it to work with local urls that start with "file:///". Is there a special syntax for this?

**Comment by sylouuu** [comment]
Hey @ndeubert,

It only works on websites because it's based on `[location.href](https://github.com/sylouuu/chrome-tab-modifier/blob/release/0.5.0/src/js/content.js#L9)`. Moreover, the extension can't access to local files except if you have a website with a virtual host. Something like "localhost/...", "my-website.local"...

**Comment by sylouuu** [comment]
I reopen this issue because I've found something about `file://` access.

**Comment by sylouuu** [comment]
Hi @ndeubert,

Acutally, it's possible, see [this commit](https://github.com/sylouuu/chrome-tab-modifier/commit/5a64229ab9d44625edbaf3b6b7963a2cb06c462b).

This feature is planned for release 0.6.0 at the end of the month.

Bests

**Comment by ndeubert** [comment]
Excellent, merci beaucoup! I tried making the same patch to the
manifest.json file in my google-chrome config folder but that still did not
work for me. So I also tried replacing the js and html folders with the
latest ones from git but that also did not seem to work for me either. For
reference the URL I am trying to match is like this:
"file:///scratch/svn/ssh1/index.html?10.60.16.117&debug"

and my tab_modifier.json file has this:
{
    "file://": {
        "icon": "http://localhost/logos/soundtouch_32x32.png",
        "pinned": true
    }
}

**Comment by sylouuu** [comment]
Your JSON file is OK but if you wan't to make it works just check the developer mode in chrome://extensions/.

Clone the repository & go to release/0.6.0.

```
git checkout release/0.6.0
```

Import the `chrome-tab-modifier/dist` folder in a developer extension & add your JSON.

**Comment by ndeubert** [comment]
Got it working! Thank you again.

**Comment by sylouuu** [comment]
Supported in [0.6.0](https://github.com/sylouuu/chrome-tab-modifier/releases/tag/0.6.0).

**Comment by pierrethibault** [comment]
Hello. Just wanted to point out a caveat: not working in conjunction with SSL encrypted websites.
E.g. I have the entry:
"""
{
    "mail.google.com": {
        "icon": "file:///path_to_my_favicon.png"
    }
}
"""
but the javascript console says:
"""
Mixed Content: The page at 'https://mail.google.com/mail[...]' was loaded over HTTPS, but requested an insecure favicon 'file:///path_to_my_icon.png'. This content should also be served over HTTPS.
"""

**Comment by sylouuu** [comment]
@pierrethibault 

You can't load a local favicon, you have to upload it somewhere.

This is related to detect local URL ie.:

```js
{
   "file:///path_to_my_file.html": {
        "unique": true
    }
}
```

**Comment by pierrethibault** [comment]
Alright sorry for the confusion.

**Comment by sylouuu** [comment]
Quick note to say that this case is listed in the README with few workarounds.
