### ISSUE TITLE
Slightly out of date at Opera

### ISSUE THREAD

**Issue by insign** [sylouuu/chrome-tab-modifier#135]
### Tab Modifier 0.21
**Browser:** `Opera`

_Can be found here: https://addons.opera.com/en/extensions/details/tab-modifier/_

It is slightly out of date at Opera Store. Please update :)

**Comment by sylouuu** [comment]
Finally approved by the Opera Team!

https://addons.opera.com/fr/extensions/details/tab-modifier/
