### ISSUE TITLE
Tab not displaying Renamed Text

### ISSUE THREAD

**Issue by goathahalol** [sylouuu/chrome-tab-modifier#136]
### Tab Modifier version
**Chrome version:**  65.0.3325.181
**Extension version:** `0.22.0`

### Expected behavior

Expect tab to rename and remain full sized with new name displayed

### Actual behavior

Tab shrinks to icon size and new title isn't displayed unless hovered with cursor.

### Steps to reproduce the behavior

_Please describe the steps to help me to reproduce the actual behavior_

1. Setup Rule
2. Save Rule and refresh page
3. Tab immediately shrinks to width of icon.

**Comment by sylouuu** [comment]
Hello,

This is the pinned option, just disable it in the rule.

Best

**Comment by goathahalol** [comment]
Awesome, Thanks!
