### ISSUE TITLE
is it possible to resize the tabs ?

### ISSUE THREAD

**Issue by kellogx** [sylouuu/chrome-tab-modifier#138]
Thanks a lot for the great extension. I really appreciate it.
I'd like to attend short names to tabs. But when working not many tabs size of the tabs remains big.
TLDR : Is there a way to handle the length of a tab ?

Thanks.

**Comment by sylouuu** [comment]
Hello,

Thanks for your feedback!

A tab has a max width, when the Chrome window has no more space, tabs are shrinked.

But, you can't handle yourself or programmatically the tab size.

Best
