### ISSUE TITLE
Chrome Tab modifier for "built-in" Tabs (e.g.chrome://history)

### ISSUE THREAD

**Issue by winkle28** [sylouuu/chrome-tab-modifier#14]
Unfortunately it ist not possible to change the adressbar-icons from "internal" Chrome-Adresses like
"chrome://history".

Do you know how this can be achieved or do you plan a future version to make it possible ?

Maybe you know where Chrome stores the graphic data for those "default Icons" (like the clock icon from the history tab) ?

**Comment by sylouuu** [comment]
Hi @winkle28,

As I know you can't inject any content script in `chrome://*` tabs. Ref. #11. So it's a Chrome restriction.

I don't know where Chrome stores theses icons, I've spent many times to find [this one](https://github.com/sylouuu/chrome-tab-modifier/blob/master/dist/img/default_favicon.png).

Bests

**Comment by cameronj86** [comment]
Has there been an update on this functionality on Google's end perhaps? 

I currently use "FVD Speed Dial" to customize my new tab (chrome://newtab) and they are able to change the tab name (ie [here](https://i.imgur.com/W8n0YIp.png)). 

I see that their extension has a permission called "Replace the page you see when opening a new tab" so it might be only applicable to the "newtab" and not the other "chrome://" paths.
