### ISSUE TITLE
Is it possible to use 32x32 favicons with tab modifier?

### ISSUE THREAD

**Issue by SergRZ** [sylouuu/chrome-tab-modifier#144]
When I install custom favicon it looks like 16x16, though original file was 32x32. The image looks very blurred on retina display. Picture below illustrates the difference:
<img width="369" alt="2018-05-11 20 09 23" src="https://user-images.githubusercontent.com/10130058/39937063-41b89d68-5557-11e8-8498-b9e39a7b5bb1.png">

Is it possible to use 32x32 favicons with tab modifier?

**Comment by SergRZ** [comment]
Thank You very mach! 

Everything works fine.

Best regards,
Sergey

**Comment by SergRZ** [comment]
Hello!

I found, that when using ico file that contains both 16x16 and 32x32 favicons only 16x16 favicon is used in extension configuration.

May be this behavior should be changed to allow import of 32x32 icons from ico file?

**Comment by sylouuu** [comment]
Hello,

I don't have any logic on favicons. I just put the URL inside the DOM and the browser does the job.

cf. https://github.com/sylouuu/chrome-tab-modifier/blob/release/0.22.0/src/js/content.js#L172

Best

**Comment by SergRZ** [comment]
So for taking Your time. 

It's not the extension but duri.me behavior that leaves only 16x16 favicon from ico file.
