### ISSUE TITLE
Problem with version 0.22.0, not sure if bug or I'm doing something wrong

### ISSUE THREAD

**Issue by meateaapple** [sylouuu/chrome-tab-modifier#147]
I love this extension, but a couple of months ago it abruptly stopped working. I have a lot of Google spreadsheet tabs open at once; I create a rule for a URL--say, that it contains "9AfNqMb" (a string in the URL of one of my spreadsheets). The icon to be loaded is a .png from my website, like "blah/blah/schedule.png."

When I reload the tab, the same thing always happens:

1. the tab icon appears as 
![icon](https://user-images.githubusercontent.com/7636489/40722955-b22d7a8a-63eb-11e8-9e09-ab6b7dc3cc13.png)

2. the tab icon then appears briefly as the CORRECT icon, loaded from my website; this lasts about .5 seconds

3. the tab icon then changes back to the icon mentioned in (1) above

I don't know why this started happening--I didn't change any of my rules, nor the URLs to my icons, and the extension is briefly loading the correct icon. I thought at first that it had to do with the way that Google spreadsheets load the URL, since the URL changes as you load a page, but I've minimized my rules to only include a string which does not change--i.e., it's present in each version of the URL.

I should also say that this is not unique to Google spreadsheets--it happens with every site, if I have a rule turned on.

Any advice here? I love this extension and would really love to get it working.

**Comment by meateaapple** [comment]
Hey Syl. I tried this and it worked. So the prebuilt icons work.

So I guess the problem is with my icons? Not sure why it would have worked fine before, or why it would load them very briefly now but replace them with the blank page/empty icon.

**Comment by meateaapple** [comment]
After doing some further testing, it looks like the extension isn't working whenever the image to be loaded is linked by an external URL. I have tried various URLs from my own website and from other websites as well, but none work; it always ends up with the blank page icon.

**Comment by sylouuu** [comment]
I thought It could be related to CSP but, I try to put the YouTube favicon (https://s.ytimg.com/yts/img/favicon_32-vflOogEID.png) on Twitch.tv and it works.

Can you give a favicon link that I can try?

Best

**Comment by meateaapple** [comment]
Sure. Try this one:

http://emps.me/bryce/favicons/ideas.png

**Comment by clfer** [comment]
Hello

Tested your icon with a rule on https://www.google.com/ and got the following error
> Mixed Content: The page at 'https://www.google.com/' was loaded over HTTPS, but requested an insecure favicon 'http://emps.me/bryce/favicons/ideas.png'. This request has been blocked; the content must be served over HTTPS. 

This is due to Chrome (new?) policy on mixed content.
You can only use icons served over https.

Have a good day

**Comment by meateaapple** [comment]
Got it, thanks a bunch to both of you for checking into it. I really appreciate it.

**Comment by sylouuu** [comment]
Thanks @clfer :)
