### ISSUE TITLE
Overlapping rules

### ISSUE THREAD

**Issue by connerjcole** [sylouuu/chrome-tab-modifier#15]
When there are URLs that meet criteria of multiple rules (even if they don't overlap i.e. one is just an icon and one is just a title), only one rule is fulfilled.  Is there any way to have multiple rules work together?

**Comment by sylouuu** [comment]
Hi,

The first rule found is applied.

Maybe you can find a better URL fragment for your rules?

Can you export your rules and paste the JSON here and tell me what do you want to achieve?

Bests wishes

**Comment by connerjcole** [comment]
Pasted below -- (not actual URLs & names shown)

Essentially I would like certain logos & names to appear when a particular account is pulled up on a site.  However, there is another site that also shows the same account name, and I would like this to always have the same name & icon -- i.e. doesn't change depending on account.  Since there are strings in the URL between where the account number is and the base URL, I can't really use a longer string that would capture what I need all the time.

Not super important here but just curious if there is some kind of work around.

        {
            "name": "BM - 1",
            "url_fragment": "act=4247846564527",
            "tab": {
                "title": "BM - 1",
                "icon": "https://upload.wikimedia.org/wikipedia/en/thumb/0/03/xxxx.svg.png",
                "pinned": false,
                "protected": false,
                "unique": false,
                "muted": false,
                "url_matcher": null
            }
        },
        {
            "name": "Monitor",
            "url_fragment": "/monitor",
            "tab": {
                "title": null,
                "icon": "bullets/bullet-red.png",
                "pinned": false,
                "protected": false,
                "unique": false,
                "muted": false,
                "url_matcher": null
            }
        },
        {
            "name": "BM - 2",
            "url_fragment": "act=509512558474",
            "tab": {
                "title": "BM - 2",
                "icon": "http://cdn2.hubspot.net/hub/30741/file-xxxx-jpg/blog-files/fd_social_icon.jpg?t=1446",
                "pinned": false,
                "protected": false,
                "unique": false,
                "muted": false,
                "url_matcher": null
            }
        },
        {
            "name": "BM - 3",
            "url_fragment": "act=4610696385",
            "tab": {
                "title": "BM - 3",
                "icon": "https://upload.wikimedia.org/wikipedia/en/1/13/xxxxgif",
                "pinned": false,
                "protected": false,
                "unique": false,
                "muted": false,
                "url_matcher": null
            }
        },
        {
            "name": "PE",
            "url_fragment": "powereditor",
            "tab": {
                "title": "PE",
                "icon": "bullets/bullet-blue-grey-alt.png",
                "pinned": false,
                "protected": false,
                "unique": false,
                "muted": false,
                "url_matcher": null
            }
        },
                    "name": "BM - 4",
            "url_fragment": "act=5307052754",
            "tab": {
                "title": "BM - 4",
                "icon": "http://everybodyhatesatourist.net/wp-content/uploads/2015/04/xxxxx.png",
                "pinned": false,
                "protected": false,
                "unique": false,
                "muted": false,
                "url_matcher": null
            }
        }
    ]
}

Thanks!

**Comment by sylouuu** [comment]
Hi,

As the extension can only works with the current URL, you can't do anything else...

Bests
