### ISSUE TITLE
Doesn't show data uri for favicon

### ISSUE THREAD

**Issue by cherylfahling** [sylouuu/chrome-tab-modifier#151]
### Tab Modifier version 0.22.0

**Browser:** Chrome

**Extension version:** 0.22.0

### Expected behavior

A favicon to be saved and appear in my rule.

### Actual behavior

I can save, but It's blank.

This has only started happening the last few days.  I have older data uri favicons that work just fine in my rules.

### Steps to reproduce the behavior

1. Copy and paste data uri into rule.
2. Save rule.
3.  No favicon image -- it's blank.

**Comment by sylouuu** [comment]
Hello,

* Can you try it on another website?
* Can you see any error in the Console related to Tab Modifier?

Best

**Comment by cherylfahling** [comment]
I'm sorry!  You can delete the issue.

I should have kept fiddling around first, but I was frustrated after not
getting it to work for days.

I just downloaded a png then converted it to base 64 and it works fine.

The problem is the source site, Iconfinder.  They've gone through some
changes recently.  Their data uris are now many times larger and just don't
work.

I'm so sorry for the bother.  When I can find a little extra time, I'll be
writing a five star review.  Tab Modifier is my favorite Chrome extension.

Best Regards,
Cheryl :)

**Comment by sylouuu** [comment]
Thanks for your feedback @cherylfahling!

Best
