### ISSUE TITLE
Allow user to specify the order of pinned tabs

### ISSUE THREAD

**Issue by tomasfejfar** [sylouuu/chrome-tab-modifier#152]
When using Tab Modifier to pin most used tabs to the begining, it's very useful to be able to specify order of those tabs. I.e. gmail always first, then calendar, then trello, then messenger. 

Current behvaior is that the order of tabs is random based on how fast each tabs is loaded and thus in what order they are pinned. It's not even based on the order of the tabs when opened.

**Comment by sylouuu** [comment]
I suggest you then to manually pin your tabs without TM. The order will be respected.

The problem with that feature, what about the sort when you have manually pinned tabs and auto pinned with TM?

I tried to add most common features to TM without creating a huge codebase for very specific/power user needs. Hope you'll understand this. :)

Best

**Comment by tomasfejfar** [comment]
> I suggest you then to manually pin your tabs without TM. The order will be respected.

That's unfortunatelly the exact thing I'm trying to avoid (and why I'm using the extension) as I need to do it every time I open chrome or accidentally close my main window. The idea is that I have a bookmark folder called "Starter" which I choose "Open all (4)" on, which opens my most used tabs. Then the tabs are automatically pinned. 

Hopefully chrome itself will add "always pin this domain" option or something.

**Comment by sylouuu** [comment]
Hello,

I won't develop such a feature because of multiple potential issues and conflicts.

Bests
