### ISSUE TITLE
rule detecting website but not changing favicon or protecting

### ISSUE THREAD

**Issue by jazzlw** [sylouuu/chrome-tab-modifier#156]
I have made a rule (export below), and it correctly detects the URL because it automatically pins it when I open a new page but it does not change the favicon or protect it.

The url is http://pandas.pydata.org/Pandas_Cheat_Sheet.pdf

```
{
    "settings": {
        "enable_new_version_notification": false
    },
    "rules": [
        {
            "name": "pandas cheatsheet",
            "detection": "CONTAINS",
            "url_fragment": "pandas.pydata.org/Pandas_Cheat_Sheet.pdf",
            "tab": {
                "icon": "bullets/bullet-blue.png",
                "muted": false,
                "pinned": true,
                "protected": true,
                "title": null,
                "title_matcher": null,
                "unique": false,
                "url_matcher": null
            }
        }
    ]
}
```

**Comment by sylouuu** [comment]
Hello,

It's a PDF, not an HTML page.

The pinned state acts on the tab itself, without depending on document type, so it works.

The protected and favicon options only work in the DOM of the HTML page, so it can't work for this case.

Hope it's clear now for you. :)

Regards
