### ISSUE TITLE
Whatsapp Web favicon issue

### ISSUE THREAD

**Issue by Heybrajham** [sylouuu/chrome-tab-modifier#16]
Everything works great, except when i setup the next rule

``` javascript
{
    "rules": [
        {
            "name": "Whatsapp",
            "url_fragment": "web.whatsapp.com/",
            "tab": {
                "title": "Google",
                "icon": "https://www.google.ca/favicon.ico",
                "pinned": false,
                "protected": false,
                "unique": false,
                "muted": false,
                "url_matcher": null
            }
        }
    ]
}
```

i see the google icon in the tab, but after some few seconds the whatsapp icon comes back, i guess the website is setting up back again, because it show the number of notifications.
Anyway i want to keep the favicon of google instead of whatsapp favicon.

_Thanks for the project, it's awesome!_

**Comment by sylouuu** [comment]
Hi @Heybrajham,

Thanks for your feedback.

I don't have a Whatsapp account, I can't check it. It's the first time I heard about a dynamic favicon.

I have coded something for websites with dynamic titles like Facebook or Twitter, I have to check if that can works for dynamic favicon too.

However, I can't tell you when I will take a look.

Bests

**Comment by sylouuu** [comment]
@denilsonsa By the way, any help is really appreciated about this.

I think I'm [close](http://stackoverflow.com/questions/35628086/webkitmutationobserver-cant-observe-link-tag) but not enough to fix this issue.

Bests

**Comment by sylouuu** [comment]
Hey guys,

Glad to announce you that this behavior is now handled in version **0.17.1**.

Bests

**Comment by brumasribera** [comment]
Actually it doesn't, I change the whatsapp icon and it goes back to the original once I get the first message.
