### ISSUE TITLE
Rule Not Working

### ISSUE THREAD

**Issue by maicart** [sylouuu/chrome-tab-modifier#162]
I have created a rule with the following details:

Name: TRANSLATOR
Detection: Exact
URL fragment: https://docs.google.com/spreadsheets/d/1L1RnMrzJ2Cfc80MGajPjIV_wg3H5WA33ag32MQwaXoc/edit#gid=908292564

Title: TRANSLATOR
Select icon: BLUE
Pinned

After clicking on "SAVE" the rule does not work.

I've already tried refreshing tab, deleting rule and doing it again, but it doesn't work.

Could you please check? Thanks

**Comment by sylouuu** [comment]
I suspect the URL to be not finalized at loading. I suggest you to create a rule with the detection "Contains" and the URL fragment like: `1L1RnMrzJ2Cfc80MGajPjIV_wg3H5WA33ag32MQwaXoc/edit#gid=908292564`

Best

**Comment by maicart** [comment]
@sylouuu Thanks for your quick answer.
I changed the rule to "Contains" but it does not work.
I created two other pinned tabs and they work fine. The difference is that the two tabs that work end in "edit#gid=0" and the one that does not work ends in "edit#gid=908292564" and contains a script.
Could that be the problem?

**Comment by maicart** [comment]
@sylouuu I think I solved it. I changed the rule to: 

Detection: "Ends with" edit#gid=908292564

And it works!

**Comment by sylouuu** [comment]
Glad for you!

Best
