### ISSUE TITLE
Chrome 69?

### ISSUE THREAD

**Issue by mmuelly** [sylouuu/chrome-tab-modifier#164]
### Tab Modifier version

**Browser:** Chrome 69.0.3497.100

**Extension version:** 0.22.0

### Steps to reproduce the behavior

_Please describe the steps to help me to reproduce the actual behavior_

Rules do not work. I have two simple rules "Contains: calendar.google.com" and none of the functionality works.  Can someone verify that the extension works with the latest Chrome 69 release?

**Comment by carrben12** [comment]
Can't confirm.  ALl my rules stopped working recently and I was wondering if the chrome update was involved. I see my custom icons for maybe ~1 second after the page loads, then they disappear.

**Comment by mmuelly** [comment]
> Works for me.
> 
> May be an issue with specific websites.

Seems universal on my end. What OS are you on?

**Comment by sylouuu** [comment]
@mmuelly 

* Windows 10 Chrome 69 : OK
* macOS Mojave Chrome 69 : OK

Rule: URL fragment "google.com" type "Contains" and title "hello"

Best

**Comment by mmuelly** [comment]
yeah, no luck on high sierra.

**Comment by mmuelly** [comment]
Problem was a security policy which prevents the extension from working correctly.

**Comment by carrben12** [comment]
a security policy setting in the browser? If you could comment on the solution that would be helpful, because I'm still broken over here.
