### ISSUE TITLE
Un-apply rules when changing URL

### ISSUE THREAD

**Issue by kaspernj** [sylouuu/chrome-tab-modifier#17]
I would like to suggest an option to un-apply rules, once the URL changes and isn't matched any more.

Example:

1. Create a rule matching youtube.com that pin's the tab
2. Open a new tab and go to youtube.com
3. Tab gets pinned and moved to the left
4. Go to github.com
5. I would now wish that the tab got unpinned

**Comment by sylouuu** [comment]
Hi @kaspernj,

What about this case, consider you have the extension installed without any rule:

1. Go to github.com
2. Right click, pin the tab
3. Reload, the tab is unpinned because there is no rule with github.com

Thx for your feedback,

Bests

**Comment by kaspernj** [comment]
I would imagine that the extension would keep track of which tabs, that it has applied rules to (and also which rules it has applied). It would use this information to roll any applied rules back, when the rule isn't matched any longer.

**Comment by sylouuu** [comment]
Hi @kaspernj,

It involves too much work to support this edge case. Hope this is OK for you if I skip this.

Bests
