### ISSUE TITLE
Feature Request:  No Icon

### ISSUE THREAD

**Issue by gitanO0** [sylouuu/chrome-tab-modifier#170]
I have some tabs up that display dynamic data in the title, but I have so many tabs open that all I see is the silly, static icon.  Is there a way to either move the icon to the end and the data first or remove it entirely?

**Comment by sylouuu** [comment]
Hello,

Chrome does not allow icon moving in the tab.
Chrome will display a default icon if none is found.

An extension can't handle these cases.

Best
