### ISSUE TITLE
Feature Request:  Allow custom tab sizes

### ISSUE THREAD

**Issue by gitanO0** [sylouuu/chrome-tab-modifier#171]
I usually have many tabs open, such that they are all reduced to the size of the tab icon.  Would it be possible to create within the rules, a setting to custom size individual tabs, ideally to match the size of the data in the title.

**Comment by sylouuu** [comment]
Hello,

The tab size is handled by Chrome itself, depending of the window size and how many tabs are open.

We can't customize this.

Best
