### ISSUE TITLE
Don't show the DOM content reference when the content contains no value

### ISSUE THREAD

**Issue by timarthurlee** [sylouuu/chrome-tab-modifier#174]
### Tab Modifier version

**Browser:** `Chrome`

**Extension version:** `0.22.0`

_Can be found here: chrome://extensions/?id=hcbgadmbdkiilgpifjgcakjehmafcjai_

### Expected behavior

_Display nothing where {title} is entered_

### Actual behavior

_It currently displays "{title}"_

### Steps to reproduce the behavior

_Please describe the steps to help me to reproduce the actual behavior_

1. Use {title} in the title field on a page with no title
2. Refresh the page

**Comment by MartinLichtblau** [comment]
Why would you create a title rule that returns no value and thus keeps title unchanged?

**Comment by sylouuu** [comment]
@timarthurlee It's a duplicate with https://github.com/sylouuu/chrome-tab-modifier/issues/74

Best

**Comment by MartinLichtblau** [comment]
Fixed it together with issue #168.
