### ISSUE TITLE
improper handling of Regular Expressions

### ISSUE THREAD

**Issue by PeteWheelwright** [sylouuu/chrome-tab-modifier#175]
### Tab Modifier RegEx
**Browser:** `Opera`
**Extension version:** `0.22.0`
Can be found here: https://addons.opera.com/en/extensions/details/tab-modifier/

The way this Extension implements Regular Expressions is wrong!
Your example RegEx does not escape special characters (the forward slash in this case):
`github[.]com/([A-Za-z0-9_-]+)/([A-Za-z0-9_-]+)`

correct **RegEx** should be like this:
`github[.]com\/([A-Za-z0-9_-]+)\/([A-Za-z0-9_-]+)`

or
`https?:\/\/(|w{3}\.)github\.com\/([\w-]+)\/([\w-]+)`
to match the protocol and web standard

Example **RegEx** to match a webpage:
`https?:\/\/(|w{3}\.)example\.com\/([\w-]+)\.html`

would match following sites:
`http://www.example.com/page_1.html`
`https://www.example.com/page_2.html`
`http://example.com/page_1.html`
`https://example.com/page_2.html`

I created two sample sites on my domain for testing purpose:
[http://1info.tk/page1.html](http://1info.tk/page1.html)
[http://1info.tk/page2.html](http://1info.tk/page2.html)

Their current page title is _"Hello World!"_
What would be the correct syntax for **your** Extension to change their titles to "Testpage 1" or "Testpage 2" respectively? 

A **_proper_** **RegEx** for matching could be:
`https?:\/\/(|w{3}\.)1info\.tk\/([a-zA-Z-]+)([0-9])+\.html`

and the corresponding **_proper_** **RegEx** for replacing:
`Test\2 \3`

**Comment by sylouuu** [comment]
Hello,

Check out the source: https://github.com/sylouuu/chrome-tab-modifier/blob/master/src/js/content.js

Search for `new RegExp` you'll find out how the way it's handled.

Best

**Comment by PeteWheelwright** [comment]
Thanks!

It seems that I made a mistake in the pattern. The forward slash doesn't need to be escaped. If escaped the pattern doesn't match.

As in [ECMAScript-262 ](http://www.ecma-international.org/ecma-262/5.1/#sec-15.10.1) the following characters should be escaped:
`^ $ \ . * + ? ( ) [ ] { } |`

Kind regards
Pete
