### ISSUE TITLE
Focus switch when typing new address

### ISSUE THREAD

**Issue by kaspernj** [sylouuu/chrome-tab-modifier#18]
1. Create a filter for a unique and pinned tab: www.facebook.com
2. Open a new tab
3. Start typing a new address "face", don't press enter and wait 2 seconds
4. Before pressing enter the focus is switched to the Facebook tab and the new tab remains open

OS X El Capitan
Chrome: Version 48.0.2564.116 (64-bit)

If I disable the extension and do it, then it works fine and doesn't switch focus.

I would expect it not to switch focus. If I finish the address with "www.facebook.com" I would expect the tab to close and the focus to switch to the already opened tab. If I finish the address with something else than Facebook, then I would expect the new tab to behave as without the extension enabled.

**Comment by sylouuu** [comment]
Hi @kaspernj,

Just pointed out the issue. It's a mix between the Chrome Omnibox preload and the "New tab" tab which is a system tab with restrictions access.

I'll do more tests to be sure that this unexpected behavior is solved.

Bests
