### ISSUE TITLE
Reload popup on Chrome

### ISSUE THREAD

**Issue by vincenormand** [sylouuu/chrome-tab-modifier#183]
### Tab Modifier version
0.22.0

**Browser:** `Chrome`
**Extension version:** `72.0.3626.121`

### Actual behavior

We use **Azure DevOps** at work and are a having an issue with pinned tabs.
When you reload a pinned page (Reload button or F5), the following popup appears and ask you to confirm the reload even tho there is nothing to be saved.

![2019-03-18 09_43_53-Window](https://user-images.githubusercontent.com/9322382/54534723-5cdba800-4963-11e9-9231-5e00005af986.jpg)

This seems to happen only in Azure DevOps, and i don't know if it is possible to fix.

### Expected behavior

When i click the "Reload" button in Chrome to reload a page, I expect the page to reload without having a popup asking me to confirm the Reload.

**Comment by sylouuu** [comment]
Hello @vincenormand 

Do you have the "protected" option enabled on the rule?

Best

**Comment by vincenormand** [comment]
Hi,

Yes it is enabled. I thought it would only trigger if I closed the tab, but it seems to be triggered also for a page reload.

I will disable the "protected" option, as it is not a must for me. If it can be fixed, great! If not, it is not a big issue.

Thank you for pointing me to the "protected" option !

**Comment by sylouuu** [comment]
It's not fixable. Unfortunately, there is the same event triggered by the browser when you leave or reload a page. Some users have already reported this issue: #83 and #28.

Best
