### ISSUE TITLE
Gmail tabs not being modified

### ISSUE THREAD

**Issue by quincy2112** [sylouuu/chrome-tab-modifier#191]
### Tab Modifier version
**Browser:** `Chrome` or `Opera`
Chrome version 75.0.3770.100
**Extension version:** `X.Y.Z`
0.22.0

_Can be found here: https://chrome.google.com/webstore/detail/tab-modifier/hcbgadmbdkiilgpifjgcakjehmafcjai?hl=en

### Expected behavior
Setting a rule with "contains google.com" or "contains mail.google.com" should trigger the rule when gmail is opened (with the URL mail.google.com).

### Actual behavior

No rules are triggered with gmail, although on google.com or google searches the rules trigger normally.

### Steps to reproduce the behavior

1. Create new rule with condition "contains google.com"
2. Open mail.google.com
3. Rule isn't triggered

**Comment by sylouuu** [comment]
Hi @quincy2112 

I just tried and it works. Can you export your tab rules and paste the JSON here please?

Best

**Comment by quincy2112** [comment]
{
    "settings": {
        "enable_new_version_notification": false
    },
    "rules": [
        {
            "name": "Google",
            "detection": "CONTAINS",
            "url_fragment": "google.com",
            "tab": {
                "icon": null,
                "muted": false,
                "pinned": true,
                "protected": false,
                "title": null,
                "title_matcher": null,
                "unique": false,
                "url_matcher": null
            }
        }
    ]
}

**Comment by quincy2112** [comment]
Tested with drive.google.com and it didn't work either, if that helps.

**Comment by sylouuu** [comment]
This rule should pin the tab. Is the tab already pinned?

Disable Pinned mode and set any title and refresh the tab.

**Comment by quincy2112** [comment]
It's not pinned already. But I did as you said and changed the title, and I'm still getting the same problem. Google.com has its title changing to test, and nothing is happening to https://mail.google.com/mail/u/0/#inbox

{
    "settings": {
        "enable_new_version_notification": false
    },
    "rules": [
        {
            "name": "Google",
            "detection": "CONTAINS",
            "url_fragment": "google.com",
            "tab": {
                "icon": null,
                "muted": false,
                "pinned": false,
                "protected": false,
                "title": "Test",
                "title_matcher": null,
                "unique": false,
                "url_matcher": null
            }
        }
    ]
}

**Comment by sylouuu** [comment]
![Capture](https://user-images.githubusercontent.com/2300259/61244943-a68aa280-a74b-11e9-915b-f76160880776.PNG)

I'm doing the same and it's OK. Can you open the Developer Console and check if any error is raised?

**Comment by quincy2112** [comment]
Yes, seems like you're onto something there.

Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.

**Comment by sylouuu** [comment]
Another extension on your Chrome may interfer with Tab Modifier, can you disable all extensions and let TM enabled and try again?

See: https://stackoverflow.com/questions/54619817/how-to-fix-unchecked-runtime-lasterror-could-not-establish-connection-receivi

**Comment by quincy2112** [comment]
That didn't help, unfortunately.

**Comment by sylouuu** [comment]
Weird!

If you disable TM and refresh the tab with the console, the error message remains or disapears?

**Comment by quincy2112** [comment]
It remains.

There are other error messages besides that one, but that's the only one that appears in both mail.google.com and drive.google.com, so it's most likely the culprit here.

**Comment by sylouuu** [comment]
I have the same error on gmail without the TM extension. It's raised by Hangout chat and not related to your issue.

Can you try a rule on another website? Like here github.com?

**Comment by quincy2112** [comment]
It works correctly. 

Other google pages, like google.com or google translate, work fine. They don't have the Hangout chat error either.

**Comment by sylouuu** [comment]
Ok great, not sure if this will work for you in the future in mail.google.com...

Thanks for your feedback. If you consider the issue as closed, I let you close it!

Best

**Comment by quincy2112** [comment]
That's disappointing, it was gmail I wanted to use the extension for. Do you think the error message could be at all related, or is it a coincidence? 

Thanks for the help.

**Comment by sylouuu** [comment]
I have the same message and TM is working fine on my computing for gmail. So hard to understand where/why this is not working for you.

The previous issue is on the same topic: https://github.com/sylouuu/chrome-tab-modifier/issues/190

I can't reproduce the "error" on Windows or Mac. :(

**Comment by quincy2112** [comment]
Okay, well thanks for the help.
