### ISSUE TITLE
Not able to see any text in configuration screens

### ISSUE THREAD

**Issue by menathan** [sylouuu/chrome-tab-modifier#20]
Not sure why, but text does not display. I'm running Chrome Version 49.0.2623.110 m
See screenshot here: ![2-04-2016 20-00-30](https://cloud.githubusercontent.com/assets/1514383/14228172/f12f4ca4-f90d-11e5-8d99-d16ce1a835b8.png)

**Comment by menathan** [comment]
Just saw there were already similar issues created. Closing this one.

**Comment by sylouuu** [comment]
Hey @menathan, hope the other issue linked in the README can give you some answers.

Bests

**Comment by sylouuu** [comment]
Fira Sans will not be a problem anymore, the fond has been removed in 0.12.1.
