### ISSUE TITLE
doesn't work on pdf

### ISSUE THREAD

**Issue by MarvelWild** [sylouuu/chrome-tab-modifier#201]
steps: open
http://o7.by/static/tmp/test.pdf
now title ok,

then
hit refresh

rule: http://o7.by/static/tmp/test.pdf
title: 111

expected: title '111'
have: title 'test.pdf'

**Comment by sylouuu** [comment]
Hi @MarvelWild 

This is documented on the README. You have to authorize the extension: https://github.com/sylouuu/chrome-tab-modifier#local-files-file

Best

**Comment by MarvelWild** [comment]
Changed this option. 
Now title changes for 0.5sec to what i want, then it gets overwritten back by pdf title.
