### ISSUE TITLE
It's isn't downloaded

### ISSUE THREAD

**Issue by Sha-two** [sylouuu/chrome-tab-modifier#209]
_In case of bug report, please fill this template and remove italic lines_
_Otherwise, clear all and type :)_

### Tab Modifier version: current

**Browser:** `Chrome

**Extension version:**:current

_Can be found here: chrome://extensions/?id=hcbgadmbdkiilgpifjgcakjehmafcjai_

### Steps to reproduce the behavior
Refreshing the page before fully downloading

_Please describe the steps to help me to reproduce the actual behavior_

1. open the tab modifier in the chrome store
2. download
3. refresh page before the download has been finished

the end result is an error page saying item is already being downloaded & added to chrome

**Comment by sylouuu** [comment]
Hello,

You are the only one to report this. This must be caused by Chrome itself, not the extension. Reboot your computer and check if the extension is installed.

Best
