### ISSUE TITLE
List of rules: Unbreakable strings overflow under control buttons.

### ISSUE THREAD

**Issue by LeYvan** [sylouuu/chrome-tab-modifier#21]
Exemple in the top right of this screencap:
![image](https://cloud.githubusercontent.com/assets/8899456/14563973/714be9e0-02f2-11e6-8844-ba16f7e607db.png)

**Comment by sylouuu** [comment]
Hey @LeYvan,

Thanks for your feedback. This display issue has been fixed in 0.9.4. Please update Tab Modifier.

Bests
