### ISSUE TITLE
starting with static profile path as user1, and relogin as user2 rules do not apply

### ISSUE THREAD

**Issue by huglester** [sylouuu/chrome-tab-modifier#218]
### Tab Modifier version

**Browser:** `Chrome` 

**Extension version:** `0.22.0`

### Expected behavior

Have two users on machine. And using shortcut with path to profile directory.
I login as user 1, add rule
then login as user2 - want same rules to apply

### Actual behavior

After I login as user2, I need to reinstall the extenstion, as well as re-add rules...

### Steps to reproduce the behavior

1. login as user1
2. start chrome with params: --user-data-dir="C:\chrome_profile"
3. install extention, add rules 
4. login as user2 - and nothing works. extention will be installed but in some "broken' state

**Comment by sylouuu** [comment]
Hello,

Extensions are associated to a Chrome profile, either a local profile or a Google profile. This is not related to the extension itself.

Best regards

**Comment by huglester** [comment]
Hello

look - chrome://version shows this same path, no matter from which *logged in user" I open the chrome shortcut

C:\chrome\data\xxx\Default

shortcut params are as follows:
--user-data-dir="C:\chrome\data\xxx"


are you sure you can't do anything here?

Maybe any tips or suggestions?

thanks

**Comment by sylouuu** [comment]
Yes I'm sure I can't do anything for this, this how Chrome works.

Best regards

**Comment by huglester** [comment]
How I can contact you for some chat? I found your github page - but contact link at the bottom does not work, tried DM you in twitter also no luck. Maybe you got telegram? my username is same as here it github - huglester

thanks
