### ISSUE TITLE
Title based on html in page

### ISSUE THREAD

**Issue by SeattleMatt** [sylouuu/chrome-tab-modifier#22]
I am wondering if it is possible to have this tool grab a block of html from a page to use in the title.
For example I have 100 windows open using salesforce, however all of the windows titles just say "case # "  I'd rather have it look into the web page and extract and display this html div tag to my tab's title is "TITLE OF MY CASE"

<div class="efhpTitle" title="TITLE OF MY CASE"></div>

**Comment by sylouuu** [comment]
Hello @SeattleMatt,

Thanks for your feedback, your idea is very good and this will not break the current `{title}` variable.

I have something for you, what about this title: `{#customer_name}`?

This will retrieve the content of `#customer_name`, e.g. `<span id="customer_name">Google</span>`.

Actually, you can inject any CSS valid selector inside curly braces.

What do you think?

Bests

**Comment by SeattleMatt** [comment]
Yes, I believe this would work, in this example I would use the line
{#efhpTitle} in the Title field?

while the content of the page contains
<div class="efhpTitle" title="TITLE OF MY PAGE"</div>

Is this functionality already built in or are you proposing to add it?

**Comment by SeattleMatt** [comment]
I'm not sure why github closed this in my name, I can't seem to re-open.

**Comment by sylouuu** [comment]
Alright, this feature will be available in the next version 0.10.0.

I'll release it in few days.

Bests

**Comment by sylouuu** [comment]
Version 0.10.0 released!
