### ISSUE TITLE
Switching to pinned tabs on refresh

### ISSUE THREAD

**Issue by Alexalder** [sylouuu/chrome-tab-modifier#23]
I set some tabs to auto pin and unique. When they get automatically refreshed i think Chrome sees it as me trying to open a new one so it auto switches to that tab instead. Is there a way to avoid this?
Thanks

**Comment by sylouuu** [comment]
Hey @Alexalder, when a duplicate tab is detected, this tab is removed and the original tab is focused.

There is no way to change this behavior at this moment, for some people this is the expected behavior.

Bests

**Comment by Alexalder** [comment]
Well ok, but this is not a duplicate tab, it's just the same tab auto reloading due to a script (usual stuff in news websites for example). Definitely not expected behavior.
Maybe i'm bad at explaining myself

**Comment by sylouuu** [comment]
Can you give me the steps to reproduce this case?

Bests

**Comment by Alexalder** [comment]
Sure :D 
This is my config file 
[tab_modifier.zip](https://github.com/sylouuu/chrome-tab-modifier/files/239160/tab_modifier.zip)

Just open http://www.ansa.it/ switch to a new tab and wait around one minute for it to refresh automatically (to load incoming news)

**Comment by sylouuu** [comment]
This is fixed in 0.10.1, go to chrome://extensions/, enable the developer mode and press the update button.

Refresh your tabs and it would be OK.

Bests
