### ISSUE TITLE
Pinned not working

### ISSUE THREAD

**Issue by jmgdvt** [sylouuu/chrome-tab-modifier#24]
Dear,
I just try using tam modifier for opera, and bellow is the script that I want to use to pin all 5 site, but none of them pinned, can you help me what wrong with script ?

Thank you in advance. 

PS: I'm using opera 37 on PC

```json
{
	"rules": [{
		"name": "Gmail",
		"url_fragment": "mail.google.com/mail/u/0/?#inbox",
		"tab": {
			"title": null,
			"icon": null,
			"pinned": true,
			"protected": false,
			"unique": false,
			"muted": false,
			"url_matcher": null
		}
	}, {
		"name": "ID-BB",
		"url_fragment": "mail.google.com/mail/u/1/#inbox",
		"tab": {
			"title": null,
			"icon": null,
			"pinned": true,
			"protected": false,
			"unique": false,
			"muted": false,
			"url_matcher": null
		}
	}, {
		"name": "Office",
		"url_fragment": "mail.google.com/mail/u/2/#inbox",
		"tab": {
			"title": null,
			"icon": null,
			"pinned": true,
			"protected": false,
			"unique": false,
			"muted": false,
			"url_matcher": null
		}
	}, {
		"name": "Yahoo",
		"url_fragment": "mg.mail.yahoo.com/neo/",
		"tab": {
			"title": null,
			"icon": null,
			"pinned": true,
			"protected": false,
			"unique": false,
			"muted": false,
			"url_matcher": null
		}
	}, {
		"name": "Feedly",
		"url_fragment": "feedly.com/i/latest",
		"tab": {
			"title": null,
			"icon": null,
			"pinned": true,
			"protected": false,
			"unique": false,
			"muted": false,
			"url_matcher": null
		}
	}]
}
```

**Comment by sylouuu** [comment]
Hello @jmgdvt,

Chrome based extension are not supported by Opera.

As mentioned in the repository name, **chrome**-tab-modifier, I'm only supporting Google Chrome browser.

I don't know if you talk about the other extension [Modify O Tabs](https://addons.opera.com/fr/extensions/details/modify-o-tabs/) based on an older version of Tab Modifier and not made by me.

Otherwise I'm interested how could you install [Tab Modifier](https://chrome.google.com/webstore/detail/tab-modifier/hcbgadmbdkiilgpifjgcakjehmafcjai) on Opera browser.

Bests

**Comment by jmgdvt** [comment]
Oh... I c,

I'm sorry, because I talk about Modify O Tabs, actually.

Anyway, thank you for reply, have a nice day.

On Fri, May 13, 2016 at 2:40 PM, Syl <notifications@github.com> wrote:

> Hello @jmgdvt <https://github.com/jmgdvt>,
>
> Chrome based extension are not supported by Opera.
>
> As mentioned in the repository name, *chrome*-tab-modifier, I'm only
> supporting Google Chrome browser.
>
> I don't know if you talk about the other extension Modify O Tabs
> <https://addons.opera.com/fr/extensions/details/modify-o-tabs/> based on
> an older version of Tab Modifier and not made by me.
>
> Otherwise I'm interested how could you install Tab Modifier
> <https://chrome.google.com/webstore/detail/tab-modifier/hcbgadmbdkiilgpifjgcakjehmafcjai>
> on Opera browser.
>
> Bests
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/sylouuu/chrome-tab-modifier/issues/24#issuecomment-218973023>
>



-- 
Sincerely,

•Ju Ming•

**Comment by sylouuu** [comment]
Good news here, Tab Modifier is now available for **[Opera Browser](https://addons.opera.com/fr/extensions/details/tab-modifier/)**.
