### ISSUE TITLE
Fira Sans problem in Chrome

### ISSUE THREAD

**Issue by DavidHnilica** [sylouuu/chrome-tab-modifier#25]
Hej, 
I've tried the extension, but it seems that Chrome seems to be having some troubles rendering the Fira Sans font that You've decided to use. 

I'm not sure if it's just my case - googling returns quite a few results for the same thing, so I presume it's not THAT uncommon. 

Any chance You could use another and/or more general typeface in the next releases? 

Since You're using it pretty much everywhere, the unfortunate result of this bug is that the extension displays without any text whatsoever... Kinda nasty unless You're used to work with webdev / chrome extensions... 

![image](https://cloud.githubusercontent.com/assets/6661517/15472647/87be1676-20fc-11e6-873f-c63c1d709545.png)

**Comment by sylouuu** [comment]
Hey @DavidHnilica,

Already reported in #19, #20, see the readme file. :)

I don't know if I'll let this font face as many have troubles with it.

Bests

**Comment by sylouuu** [comment]
Fira Sans will not be a problem anymore, the fond has been removed in 0.12.1.
