### ISSUE TITLE
Rule Limit

### ISSUE THREAD

**Issue by Mortdestro** [sylouuu/chrome-tab-modifier#26]
A recent change erased all of my rules. Luckily I have my json file, but when I import it, it tells me it was successfully imported, but doesn't add the rules back. I can only seem to import/create up to 33 rules now. When I try to add a 34th, it shows up, and tells me it's successful, but when I click to Settings and then back to Rules, it's gone. This may be related to the recent storage change.

If increasing the limit is not an option, another solution for my scenario would be to allow rules to work with each other. I have all these different rules because I manually mapped a dozen or so GET variable IDs to 4 pages that use them (e.g. "www.website.com/InfoPage.aspx?ID=1234"), so if there could be a priority system where I can define one fragment ("www.website.com/InfoPage.aspx") to mean "Info Page" and then another fragment ("ID=1234") to mean "ABCD {title}" so it would say "ABCD Value Info Page", that would greatly reduce the number of rules I need. As it was, I had to look for each combination of URL and ID individually.

**Comment by sylouuu** [comment]
Hello @Mortdestro,

Could you paste the JSON content here please?

Bests

**Comment by Mortdestro** [comment]
The actual content is confidential, but here is a scrubbed version with the same idea:

{
    "rules": [
        {
            "name": "Client A Client Info",
            "url_fragment": "https://www.website.com/live/pages/ClientInfo.aspx?ID=100056653",
            "tab": {
                "title": "Client A Client Info",
                "icon": null,
                "pinned": false,
                "protected": false,
                "unique": false,
                "muted": false,
                "url_matcher": null
            }
        },
        {
            "name": "Client A ySQL",
            "url_fragment": "https://www.website.com/live/pages/SQL.aspx?ID=100056653",
            "tab": {
                "title": "Client A ySQL",
                "icon": null,
                "pinned": false,
                "protected": false,
                "unique": false,
                "muted": false,
                "url_matcher": null
            }
        },
        {
            "name": "Client A File Manager",
            "url_fragment": "https://www.website.com/live/pages/FileManager.aspx?ID=100056653",
            "tab": {
                "title": "Client A File Manager",
                "icon": null,
                "pinned": false,
                "protected": false,
                "unique": false,
                "muted": false,
                "url_matcher": null
            }
        },
        {
            "name": "Client A Package Manager",
            "url_fragment": "https://www.website.com/live/pages/LoadSQL.aspx?ID=100056653",
            "tab": {
                "title": "Client A Package Manager",
                "icon": null,
                "pinned": false,
                "protected": false,
                "unique": false,
                "muted": false,
                "url_matcher": null
            }
        },
        {
            "name": "Client B Client Info",
            "url_fragment": "https://www.website.com/live/pages/ClientInfo.aspx?ID=100039226",
            "tab": {
                "title": "Client B Client Info",
                "icon": null,
                "pinned": false,
                "protected": false,
                "unique": false,
                "muted": false,
                "url_matcher": null
            }
        },
        {
            "name": "Client B ySQL",
            "url_fragment": "https://www.website.com/live/pages/SQL.aspx?ID=100039226",
            "tab": {
                "title": "Client B ySQL",
                "icon": null,
                "pinned": false,
                "protected": false,
                "unique": false,
                "muted": false,
                "url_matcher": null
            }
        },
        {
            "name": "Client B File Manager",
            "url_fragment": "https://www.website.com/live/pages/FileManager.aspx?ID=100039226",
            "tab": {
                "title": "Client B File Manager",
                "icon": null,
                "pinned": false,
                "protected": false,
                "unique": false,
                "muted": false,
                "url_matcher": null
            }
        },
        {
            "name": "Client B Package Manager",
            "url_fragment": "https://www.website.com/live/pages/LoadSQL.aspx?ID=100039226",
            "tab": {
                "title": "Client B Package Manager",
                "icon": null,
                "pinned": false,
                "protected": false,
                "unique": false,
                "muted": false,
                "url_matcher": null
            }
        },
        {
            "name": "Client BR Client Info",
            "url_fragment": "https://www.website.com/live/pages/ClientInfo.aspx?ID=100034278",
            "tab": {
                "title": "Client BR Client Info",
                "icon": null,
                "pinned": false,
                "protected": false,
                "unique": false,
                "muted": false,
                "url_matcher": null
            }
        },
        {
            "name": "Client BR ySQL",
            "url_fragment": "https://www.website.com/live/pages/SQL.aspx?ID=100034278",
            "tab": {
                "title": "Client BR ySQL",
                "icon": null,
                "pinned": false,
                "protected": false,
                "unique": false,
                "muted": false,
                "url_matcher": null
            }
        },
        {
            "name": "Client BR File Manager",
            "url_fragment": "https://www.website.com/live/pages/FileManager.aspx?ID=100034278",
            "tab": {
                "title": "Client BR File Manager",
                "icon": null,
                "pinned": false,
                "protected": false,
                "unique": false,
                "muted": false,
                "url_matcher": null
            }
        },
        {
            "name": "Client BR Package Manager",
            "url_fragment": "https://www.website.com/live/pages/LoadSQL.aspx?ID=100034278",
            "tab": {
                "title": "Client BR Package Manager",
                "icon": null,
                "pinned": false,
                "protected": false,
                "unique": false,
                "muted": false,
                "url_matcher": null
            }
        },
        {
            "name": "Client BL Client Info",
            "url_fragment": "https://www.website.com/live/pages/ClientInfo.aspx?ID=100036879",
            "tab": {
                "title": "Client BL Client Info",
                "icon": null,
                "pinned": false,
                "protected": false,
                "unique": false,
                "muted": false,
                "url_matcher": null
            }
        },
        {
            "name": "Client BL ySQL",
            "url_fragment": "https://www.website.com/live/pages/SQL.aspx?ID=100036879",
            "tab": {
                "title": "Client BL ySQL",
                "icon": null,
                "pinned": false,
                "protected": false,
                "unique": false,
                "muted": false,
                "url_matcher": null
            }
        },
        {
            "name": "Client BL File Manager",
            "url_fragment": "https://www.website.com/live/pages/FileManager.aspx?ID=100036879",
            "tab": {
                "title": "Client BL File Manager",
                "icon": null,
                "pinned": false,
                "protected": false,
                "unique": false,
                "muted": false,
                "url_matcher": null
            }
        },
        {
            "name": "Client BL Package Manager",
            "url_fragment": "https://www.website.com/live/pages/LoadSQL.aspx?ID=100036879",
            "tab": {
                "title": "Client BL Package Manager",
                "icon": null,
                "pinned": false,
                "protected": false,
                "unique": false,
                "muted": false,
                "url_matcher": null
            }
        },
        {
            "name": "Client E Client Info",
            "url_fragment": "https://www.website.com/live/pages/ClientInfo.aspx?ID=100058980",
            "tab": {
                "title": "Client E Client Info",
                "icon": null,
                "pinned": false,
                "protected": false,
                "unique": false,
                "muted": false,
                "url_matcher": null
            }
        },
        {
            "name": "Client E ySQL",
            "url_fragment": "https://www.website.com/live/pages/SQL.aspx?ID=100058980",
            "tab": {
                "title": "Client E ySQL",
                "icon": null,
                "pinned": false,
                "protected": false,
                "unique": false,
                "muted": false,
                "url_matcher": null
            }
        },
        {
            "name": "Client E File Manager",
            "url_fragment": "https://www.website.com/live/pages/FileManager.aspx?ID=100058980",
            "tab": {
                "title": "Client E File Manager",
                "icon": null,
                "pinned": false,
                "protected": false,
                "unique": false,
                "muted": false,
                "url_matcher": null
            }
        },
        {
            "name": "Client E Package Manager",
            "url_fragment": "https://www.website.com/live/pages/LoadSQL.aspx?ID=100058980",
            "tab": {
                "title": "Client E Package Manager",
                "icon": null,
                "pinned": false,
                "protected": false,
                "unique": false,
                "muted": false,
                "url_matcher": null
            }
        },
        {
            "name": "Client FF Client Info",
            "url_fragment": "https://www.website.com/live/pages/ClientInfo.aspx?ID=100028339",
            "tab": {
                "title": "Client FF Client Info",
                "icon": null,
                "pinned": false,
                "protected": false,
                "unique": false,
                "muted": false,
                "url_matcher": null
            }
        },
        {
            "name": "Client FF ySQL",
            "url_fragment": "https://www.website.com/live/pages/SQL.aspx?ID=100028339",
            "tab": {
                "title": "Client FF ySQL",
                "icon": null,
                "pinned": false,
                "protected": false,
                "unique": false,
                "muted": false,
                "url_matcher": null
            }
        },
        {
            "name": "Client FF File Manager",
            "url_fragment": "https://www.website.com/live/pages/FileManager.aspx?ID=100028339",
            "tab": {
                "title": "Client FF File Manager",
                "icon": null,
                "pinned": false,
                "protected": false,
                "unique": false,
                "muted": false,
                "url_matcher": null
            }
        },
        {
            "name": "Client FF Package Manager",
            "url_fragment": "https://www.website.com/live/pages/LoadSQL.aspx?ID=100028339",
            "tab": {
                "title": "Client FF Package Manager",
                "icon": null,
                "pinned": false,
                "protected": false,
                "unique": false,
                "muted": false,
                "url_matcher": null
            }
        },
        {
            "name": "Client F Client Info",
            "url_fragment": "https://www.website.com/live/pages/ClientInfo.aspx?ID=100039385",
            "tab": {
                "title": "Client F Client Info",
                "icon": null,
                "pinned": false,
                "protected": false,
                "unique": false,
                "muted": false,
                "url_matcher": null
            }
        },
        {
            "name": "Client F ySQL",
            "url_fragment": "https://www.website.com/live/pages/SQL.aspx?ID=100039385",
            "tab": {
                "title": "Client F ySQL",
                "icon": null,
                "pinned": false,
                "protected": false,
                "unique": false,
                "muted": false,
                "url_matcher": null
            }
        },
        {
            "name": "Client F File Manager",
            "url_fragment": "https://www.website.com/live/pages/FileManager.aspx?ID=100039385",
            "tab": {
                "title": "Client F File Manager",
                "icon": null,
                "pinned": false,
                "protected": false,
                "unique": false,
                "muted": false,
                "url_matcher": null
            }
        },
        {
            "name": "Client F Package Manager",
            "url_fragment": "https://www.website.com/live/pages/LoadSQL.aspx?ID=100039385",
            "tab": {
                "title": "Client F Package Manager",
                "icon": null,
                "pinned": false,
                "protected": false,
                "unique": false,
                "muted": false,
                "url_matcher": null
            }
        },
        {
            "name": "Client L Client Info",
            "url_fragment": "https://www.website.com/live/pages/ClientInfo.aspx?ID=100036335",
            "tab": {
                "title": "Client L Client Info",
                "icon": null,
                "pinned": false,
                "protected": false,
                "unique": false,
                "muted": false,
                "url_matcher": null
            }
        },
        {
            "name": "Client L ySQL",
            "url_fragment": "https://www.website.com/live/pages/SQL.aspx?ID=100036335",
            "tab": {
                "title": "Client L ySQL",
                "icon": null,
                "pinned": false,
                "protected": false,
                "unique": false,
                "muted": false,
                "url_matcher": null
            }
        },
        {
            "name": "Client L File Manager",
            "url_fragment": "https://www.website.com/live/pages/FileManager.aspx?ID=100036335",
            "tab": {
                "title": "Client L File Manager",
                "icon": null,
                "pinned": false,
                "protected": false,
                "unique": false,
                "muted": false,
                "url_matcher": null
            }
        },
        {
            "name": "Client L Package Manager",
            "url_fragment": "https://www.website.com/live/pages/LoadSQL.aspx?ID=100036335",
            "tab": {
                "title": "Client L Package Manager",
                "icon": null,
                "pinned": false,
                "protected": false,
                "unique": false,
                "muted": false,
                "url_matcher": null
            }
        },
        {
            "name": "Client MA Client Info",
            "url_fragment": "https://www.website.com/live/pages/ClientInfo.aspx?ID=100019006",
            "tab": {
                "title": "Client MA Client Info",
                "icon": null,
                "pinned": false,
                "protected": false,
                "unique": false,
                "muted": false,
                "url_matcher": null
            }
        },
        {
            "name": "Client MA ySQL",
            "url_fragment": "https://www.website.com/live/pages/SQL.aspx?ID=100019006",
            "tab": {
                "title": "Client MA ySQL",
                "icon": null,
                "pinned": false,
                "protected": false,
                "unique": false,
                "muted": false,
                "url_matcher": null
            }
        },
        {
            "name": "Client MA File Manager",
            "url_fragment": "https://www.website.com/live/pages/FileManager.aspx?ID=100019006",
            "tab": {
                "title": "Client MA File Manager",
                "icon": null,
                "pinned": false,
                "protected": false,
                "unique": false,
                "muted": false,
                "url_matcher": null
            }
        },
        {
            "name": "Client MA Package Manager",
            "url_fragment": "https://www.website.com/live/pages/LoadSQL.aspx?ID=100019006",
            "tab": {
                "title": "Client MA Package Manager",
                "icon": null,
                "pinned": false,
                "protected": false,
                "unique": false,
                "muted": false,
                "url_matcher": null
            }
        },
        {
            "name": "Client NC Client Info",
            "url_fragment": "https://www.website.com/live/pages/ClientInfo.aspx?ID=100034704",
            "tab": {
                "title": "Client NC Client Info",
                "icon": null,
                "pinned": false,
                "protected": false,
                "unique": false,
                "muted": false,
                "url_matcher": null
            }
        },
        {
            "name": "Client NC ySQL",
            "url_fragment": "https://www.website.com/live/pages/SQL.aspx?ID=100034704",
            "tab": {
                "title": "Client NC ySQL",
                "icon": null,
                "pinned": false,
                "protected": false,
                "unique": false,
                "muted": false,
                "url_matcher": null
            }
        },
        {
            "name": "Client NC File Manager",
            "url_fragment": "https://www.website.com/live/pages/FileManager.aspx?ID=100034704",
            "tab": {
                "title": "Client NC File Manager",
                "icon": null,
                "pinned": false,
                "protected": false,
                "unique": false,
                "muted": false,
                "url_matcher": null
            }
        },
        {
            "name": "Client NC Package Manager",
            "url_fragment": "https://www.website.com/live/pages/LoadSQL.aspx?ID=100034704",
            "tab": {
                "title": "Client NC Package Manager",
                "icon": null,
                "pinned": false,
                "protected": false,
                "unique": false,
                "muted": false,
                "url_matcher": null
            }
        },
        {
            "name": "Client SR Client Info",
            "url_fragment": "https://www.website.com/live/pages/ClientInfo.aspx?ID=100066364",
            "tab": {
                "title": "Client SR Client Info",
                "icon": null,
                "pinned": false,
                "protected": false,
                "unique": false,
                "muted": false,
                "url_matcher": null
            }
        },
        {
            "name": "Client SR ySQL",
            "url_fragment": "https://www.website.com/live/pages/SQL.aspx?ID=100066364",
            "tab": {
                "title": "Client SR ySQL",
                "icon": null,
                "pinned": false,
                "protected": false,
                "unique": false,
                "muted": false,
                "url_matcher": null
            }
        },
        {
            "name": "Client SR File Manager",
            "url_fragment": "https://www.website.com/live/pages/FileManager.aspx?ID=100066364",
            "tab": {
                "title": "Client SR File Manager",
                "icon": null,
                "pinned": false,
                "protected": false,
                "unique": false,
                "muted": false,
                "url_matcher": null
            }
        },
        {
            "name": "Client SR Package Manager",
            "url_fragment": "https://www.website.com/live/pages/LoadSQL.aspx?ID=100066364",
            "tab": {
                "title": "Client SR Package Manager",
                "icon": null,
                "pinned": false,
                "protected": false,
                "unique": false,
                "muted": false,
                "url_matcher": null
            }
        },
        {
            "name": "Client S Client Info",
            "url_fragment": "https://www.website.com/live/pages/ClientInfo.aspx?ID=100056130",
            "tab": {
                "title": "Client S Client Info",
                "icon": null,
                "pinned": false,
                "protected": false,
                "unique": false,
                "muted": false,
                "url_matcher": null
            }
        },
        {
            "name": "Client S ySQL",
            "url_fragment": "https://www.website.com/live/pages/SQL.aspx?ID=100056130",
            "tab": {
                "title": "Client S ySQL",
                "icon": null,
                "pinned": false,
                "protected": false,
                "unique": false,
                "muted": false,
                "url_matcher": null
            }
        },
        {
            "name": "Client S File Manager",
            "url_fragment": "https://www.website.com/live/pages/FileManager.aspx?ID=100056130",
            "tab": {
                "title": "Client S File Manager",
                "icon": null,
                "pinned": false,
                "protected": false,
                "unique": false,
                "muted": false,
                "url_matcher": null
            }
        },
        {
            "name": "Client S Package Manager",
            "url_fragment": "https://www.website.com/live/pages/LoadSQL.aspx?ID=100056130",
            "tab": {
                "title": "Client S Package Manager",
                "icon": null,
                "pinned": false,
                "protected": false,
                "unique": false,
                "muted": false,
                "url_matcher": null
            }
        },
        {
            "name": "Client V Client Info",
            "url_fragment": "https://www.website.com/live/pages/ClientInfo.aspx?ID=100052585",
            "tab": {
                "title": "Client V Client Info",
                "icon": null,
                "pinned": false,
                "protected": false,
                "unique": false,
                "muted": false,
                "url_matcher": null
            }
        },
        {
            "name": "Client V ySQL",
            "url_fragment": "https://www.website.com/live/pages/SQL.aspx?ID=100052585",
            "tab": {
                "title": "Client V ySQL",
                "icon": null,
                "pinned": false,
                "protected": false,
                "unique": false,
                "muted": false,
                "url_matcher": null
            }
        },
        {
            "name": "Client V File Manager",
            "url_fragment": "https://www.website.com/live/pages/FileManager.aspx?ID=100052585",
            "tab": {
                "title": "Client V File Manager",
                "icon": null,
                "pinned": false,
                "protected": false,
                "unique": false,
                "muted": false,
                "url_matcher": null
            }
        },
        {
            "name": "Client V Package Manager",
            "url_fragment": "https://www.website.com/live/pages/LoadSQL.aspx?ID=100052585",
            "tab": {
                "title": "Client V Package Manager",
                "icon": null,
                "pinned": false,
                "protected": false,
                "unique": false,
                "muted": false,
                "url_matcher": null
            }
        },
        {
            "name": "z_Client Info",
            "url_fragment": "https://www.website.com/live/pages/ClientInfo.aspx",
            "tab": {
                "title": "Client Info",
                "icon": null,
                "pinned": false,
                "protected": false,
                "unique": false,
                "muted": false,
                "url_matcher": null
            }
        },
        {
            "name": "z_SQL",
            "url_fragment": "https://www.website.com/live/pages/SQL.aspx",
            "tab": {
                "title": "SQL",
                "icon": null,
                "pinned": false,
                "protected": false,
                "unique": false,
                "muted": false,
                "url_matcher": null
            }
        },
        {
            "name": "z_File Manager",
            "url_fragment": "https://www.website.com/live/pages/FileManager.aspx",
            "tab": {
                "title": "File Manager",
                "icon": null,
                "pinned": false,
                "protected": false,
                "unique": false,
                "muted": false,
                "url_matcher": null
            }
        },
        {
            "name": "z_Load SQL",
            "url_fragment": "https://www.website.com/live/pages/LoadSQL.aspx",
            "tab": {
                "title": "Load SQL",
                "icon": null,
                "pinned": false,
                "protected": false,
                "unique": false,
                "muted": false,
                "url_matcher": null
            }
        }
    ]
}

**Comment by sylouuu** [comment]
Can the title be found in the page dynamically?

```json
{
	"name": "Any name",
	"url_fragment": "https://www.website.com/live/pages",
	"tab": {
		"title": "Client {#client_name}",
		"icon": null,
		"pinned": false,
		"protected": false,
		"unique": false,
		"muted": false,
		"url_matcher": null
	}
}
```

Where `#client_name` is the HTML node (id="client_name") where the name can be found.

Bests

**Comment by Mortdestro** [comment]
This works for one of the pages, but the others only contain the name as a default value in a text-type input tag, which doesn't seem to pull in when I use the input tag's ID.

**Comment by sylouuu** [comment]
So what can I do for you?

**Comment by Mortdestro** [comment]
I was hoping you could either increase the number of rules we can store, or else have a multi-pass system that can find the value of title after a previous rule has been run. So Rule 1 changes the title to "Client Info" (or "SQL" or whatever), then Rule 2 adds "Client A" ( or "Client B" etc.) to the beginning. That way I wouldn't need to define so many rules.

**Comment by sylouuu** [comment]
Sorry can't do anything like that.

Bests

**Comment by sylouuu** [comment]
Hi @Mortdestro,

Just release 0.13.0, see changelog: https://github.com/sylouuu/chrome-tab-modifier/releases

Bests

**Comment by sylouuu** [comment]
Little note here, in case you don't know, you are able to specify a regexp pattern in your rule. This will avoid you to create so many rules.

Bests
