### ISSUE TITLE
Feature requests: enable rule depending on computer

### ISSUE THREAD

**Issue by philzegore** [sylouuu/chrome-tab-modifier#27]
Hello,

I use Tab Modifier extension on my professional computer, Chrome extensions are synchronized with all my computers so when I use my personnal computer, Tab Modifier is enabled, rules are synced and I don't want it.

Is it possible to enable/disable Tab Modifier rule (or extension) depending computer on which I am connected ?

Thanks

**Comment by sylouuu** [comment]
Hi @philzegore,

You are right, rules are synced if:

- you are authed with your Google account on both browser
- you have enabled extensions sync (default behavior)

At the moment, you can't disable Tab Modifer for one computer.

I'll take a look about an option in the settings view "Disable Tab Modifier on this browser".

Bests

**Comment by sylouuu** [comment]
Hi @philzegore,

Just released 0.13.0, see changelog: https://github.com/sylouuu/chrome-tab-modifier/releases

Tab rules are not more synced.

Bests

**Comment by philzegore** [comment]
Thanks a lot !
