### ISSUE TITLE
Potentially easy question "Leave"

### ISSUE THREAD

**Issue by ivanbrezakbrkan** [sylouuu/chrome-tab-modifier#28]
Hi,

I have Asana saved as a url fragment for my account, but when I navigate throught it it always ask me if I want to "Leave". I'm guessing this is due to the "Protected" option being on or? The same happens for Pipedrive. I want the tab with Asana or Pipedrive to be pinned, but not always ask me if I want to Reload/Leave?

Thanks! :)

**Comment by sylouuu** [comment]
Hi @ivanbrezakbrkan,

Thanks for using Tab Modifier.

Could you export your tab rules and paste the JSON content in a reply? I need it to inspect your specific case.

Bests

**Comment by sylouuu** [comment]
You basically have to disable the "Protected" option on your rule.

Closing for no reply.
