### ISSUE TITLE
Doesn't work with html5 pdf viewer

### ISSUE THREAD

**Issue by devilish2o** [sylouuu/chrome-tab-modifier#29]
Hello,

I am viewing a local pdf file with the extension Pdf Viewer, the url is:

chrome-extension://oemmndcbldboiebfnladdacbdfmadadm/file:///C:/Users/agm/Downloads/funny-quotes.pdf

I cannot rename the tab. Everything else is working fine, I can rename online stuffs like gmail and yahoo emails.

Thanks for your help :)

**Comment by sylouuu** [comment]
Hi @devilish2o,

**TLDR**: This is a Chrome restriction.

The `chrome-extension://` protoctol is not supported by the Content Scripts "technology" used by Tab Modifier.

Even if you use the built-in PDF viewer (you don't need an extension to open PDF in Chrome), the page is not a "standard" web page and the content script isn't included by Chrome.

Hope this reply is OK for you.

Bests

**Comment by devilish2o** [comment]
Ok, thanks for that great extension :)
