### ISSUE TITLE
Javascript Change Title

### ISSUE THREAD

**Issue by matedon** [sylouuu/chrome-tab-modifier#3]
This is a great extension. Simple and clean.
But website is able to change tab's title with javascript.
This is bad for this extension. Example page: facebook.com.
My suggestions for problem solving are:
1.) Check every x (2-5-10-30) seconds if title changed.
2.) Monitor all ajax events and fire title check after ajax success.

**Comment by sylouuu** [comment]
Quick note @matedon in case you missed it. This issue has been fixed in [0.6.0](https://github.com/sylouuu/chrome-tab-modifier/releases/tag/0.6.0) a year ago.
