### ISSUE TITLE
Changing title of YouTube locks up Chrome

### ISSUE THREAD

**Issue by sippeangelo** [sylouuu/chrome-tab-modifier#32]
I don't know if there's anything to be done about this, but since YouTube probably change their title as well through Javascript, using this addon to change titles on YouTube sends the browser into some kind of infinite war of title changes.

**Comment by sylouuu** [comment]
Hi @sippeangelo,

Can you export your rules and paste the content here? Thank you.

Bests

**Comment by sippeangelo** [comment]
Oops, seems to have been [YouTubeCenter](https://github.com/YePpHa/YouTubeCenter) interfering...

**Comment by sylouuu** [comment]
Sorry about that!

Bests
