### ISSUE TITLE
How do I ensure that at Chrome startup the tabs appear in repeatable order?

### ISSUE THREAD

**Issue by sanjaysaigal** [sylouuu/chrome-tab-modifier#33]
I just started using this wonderful product. Now, when I fire up Chrome, the tabs don't necessarily open in the order I've listed them in Tab Rules. I expected the first to be left-most, and second tab to be to the right of the first, etc. Their final sequence (left to right) on the Chrome bar seems to vary.

Is this a bug or a feature? (Or maybe simply a stupid user trick?)

**Comment by sylouuu** [comment]
Hey @sanjaysaigal,

This is neither a bug or a feature. Tabs and rules are **independent**.

First tab loaded means first tab pinned.

It is a very special need that you suggest. It means that rules should be able to be linked between them and resulting in a huge work.

Bests

**Comment by sanjaysaigal** [comment]
I see why such a feature could be problematic to implement. I am slightly surprised that it hasn't come up earlier. At any rate, its absence isn't critical to my use of your fine work.

**Comment by sylouuu** [comment]
Thanks @sanjaysaigal, I'm closing this.

**Comment by AlfredoMASoares** [comment]
Hi there, 

It would be nice to have that kind of feature (Tab Index), like this extension
https://chrome.google.com/webstore/detail/pin-tab/dgldedkigbbalaioohedddpameekglma?utm_source=chrome-app-launcher-info-dialog

Thank you 

Alfredo

**Comment by sylouuu** [comment]
To answer you @AlfredoMASoares, I refer you to the "[Focused part](https://github.com/sylouuu/chrome-tab-modifier#focused-scope)" in README.
