### ISSUE TITLE
Feature request: allow reordering the rules

### ISSUE THREAD

**Issue by denilsonsa** [sylouuu/chrome-tab-modifier#36]
Sometimes we have multiple rules that match the same page. We need to be able to reorder the rules.

UI for reordering is usually not trivial, and usually a pain to implement. I'd suggest something like when editing a playlist in YouTube. We could have a draggable handle at the left of the rule, and the user would be able to drag-and-drop the rules using the handle.

As a workaround, we are able to reorder the rules by exporting them, editing them in a text editor, and importing them again.

**Comment by sylouuu** [comment]
Hey @denilsonsa,

I let you try the `release/0.17.0` branch and tell me what do you think. :)

Bests

**Comment by sylouuu** [comment]
Released in 0.17.0.
