### ISSUE TITLE
NO setting, text file as setting not imported

### ISSUE THREAD

**Issue by led9** [sylouuu/chrome-tab-modifier#38]
Hello,
I want try your extension, but it not have setting = see attached screen, only it appears as setting.
![1](https://cloud.githubusercontent.com/assets/7848312/18913356/d3f25d46-85a0-11e6-89b6-6cf891cc6b75.jpg)

in version in Opera extension site. - you not update?

**Comment by sylouuu** [comment]
Hey @led9,

"[Modify O Tabs](https://addons.opera.com/fr/extensions/details/modify-o-tabs/?display=en)" is a fork of Tab Modifier. So I can't do support.

Tab Modifier is currently only available for Chrome.

Bests

**Comment by sylouuu** [comment]
Good news here, Tab Modifier is now available for **[Opera Browser](https://addons.opera.com/fr/extensions/details/tab-modifier/)**.
