### ISSUE TITLE
Use Event Page instead Background Page

### ISSUE THREAD

**Issue by ArthurAssuncao** [sylouuu/chrome-tab-modifier#4]
This extension is required just in page load, event page should be used.
https://developer.chrome.com/extensions/event_pages

**Comment by sylouuu** [comment]
Hi @ArthurAssuncao,

Thank you, I will look when I have a moment!

Bests

**Comment by sylouuu** [comment]
Version 0.3.1 just released, thanks for your contribution!

Bests
