### ISSUE TITLE
Feature Request: Move tabs with hotkeys

### ISSUE THREAD

**Issue by AndyMakous** [sylouuu/chrome-tab-modifier#40]
Hi there, first I want to say that I love this extension, it's beautiful in both its design and implementation. One thing I wish Chrome had by default was the ability to move the position of tabs using hotkeys. At the moment, I'm using an extension that gives me this functionality (with the hotkeys CMD+. to go right and CMD+, to go left), but I think this would be an excellent addition to your already powerful extension.

**Comment by sylouuu** [comment]
Hey @AndyMakous,

Thanks for your feedback!

The Tab Modifier goal remains to act on targeted tabs you have specified.

You are suggesting a feature that involves all tabs. I understand that you would like to have only one extension that acts on tabs. This is important for modularization purpose to build focused extensions on small features/scopes.

If there is already extension that allows you to move tabs with hotkeys, no reason to copy that feature. Don't hesitate to share this extension here.

Hope you share/understand my position.

Bests

**Comment by AndyMakous** [comment]
Thanks for the prompt response! I do understand your position and didn't really think of the extension's goal that way. For anyone who comes across this in the future, the extension I use mentioned in the OP is [Tab Mover](https://chrome.google.com/webstore/detail/tab-mover-move-tabs-with/dbkbmgieiomjnpimkilnkkcjioecdmio).
