### ISSUE TITLE
crosh window?

### ISSUE THREAD

**Issue by kswope** [sylouuu/chrome-tab-modifier#42]
I'd like to get this to work with crosh windows but either I'm not setting it up properly or its just impossible.

So, for me, this is the "URL" of a crosh window
chrome-extension://nkoccljplnhpfnfiajclkommnmllphnl/html/crosh.html

I've tried matching the entire string, the randomish looking "nkoccljplnhpfnfiajclkommnmllphnl", and "crosh.html"

Nothing works

**Comment by kswope** [comment]
I should add it also doesn't work with file://   (starting to see a pattern here :-) )

A use case of this would be commonly used PDFs

**Comment by sylouuu** [comment]
Hi @kswope,

As I know it's impossible to load a content script inside another extension `chrome-extension://`. This is why Tab Modifier doesn't work on the given URL.

It's written in the [README](https://github.com/sylouuu/chrome-tab-modifier#chrome-system-pages-chrome) (I mentionned `chrome://` but it's the same for `chrome-extension://`.

Bests

**Comment by kswope** [comment]
I suppose file:// is the same way then, that's too bad, I like keeping pdfs open (pdfs are in browser because chromebook)
