### ISSUE TITLE
Overlay tab icon option

### ISSUE THREAD

**Issue by owzim** [sylouuu/chrome-tab-modifier#45]
Great plugin, thanks for your efforts.

I use it in similar way, as described in the [README.md](/sylouuu/chrome-tab-modifier/blob/master/README.md). What I would find useful is to be able to overlay the selected icon over the existing favicon, when having multiple local sites open, it's harder to see, which one is which, without creating a separate icon for each project.

Example: Map the green hollow circle icon to local domains, map the red circle over live domains, which then overlays the existing favicon.

It would be better to have this as an option, rather then a feature replacement.

**Comment by sylouuu** [comment]
Hi @owzim,

Thanks for your feedback!

I'm not sure to understand what do you mean by "overlay the selected icon". What the user could do? What event?

Bests

**Comment by owzim** [comment]
Additional option for overlaying the icon:

![overlay](https://cloud.githubusercontent.com/assets/1720088/20642929/421535ec-b41c-11e6-9c5f-929247d80af9.png)

Result on the tab, the green circle sits on top of the existing favicon, provided by the website:

![overlay-result](https://cloud.githubusercontent.com/assets/1720088/20642927/3aaeed98-b41c-11e6-91d4-d4ca45e6f23f.png)

Any transparent `png` should work with it. Was that a bit clearer?

**Comment by sylouuu** [comment]
Sure it's clearer now.

How do you achieve this?

**Comment by owzim** [comment]
Hi, I just looked at your code an realized you're *merely* setting the favicon in the `<head>`, simple but effective. I thought there is some Chrome API magic happening there. 

I found this interesting article on how to use a dyamic favicons rendered by a canvas, this might be a good starting point. https://remysharp.com/2010/08/24/dynamic-favicons

**Comment by bjg0** [comment]
After selecting an icon, how does one restore the original icon?

**Comment by sylouuu** [comment]
Hi @bjg0, please one issue, one problem. Create a new one next time.

To restore the original icon, clear the input next to the icon dropdown.

Bests

**Comment by bjg0** [comment]
Sorry, I'm new to github. I tried [New issue], but no response.

**Comment by sylouuu** [comment]
This is very tricky @owzim. I don't think I will follow up this issue.

You have to deal with [security restrictions](http://stackoverflow.com/questions/13674835/canvas-tainted-by-cross-origin-data), add support for async image creation into an existing sync code.

I liked the idea to support this feature for "Alt" icons but this will break existing configurations and may have unexpected results for users. Prefer to rename titles for your need.

Finally I'm not ready to spend a big work on Tab Modifier right now. Anyway thanks for you feedbacks.

Bests

**Comment by owzim** [comment]
Thanks for looking into it!
