### ISSUE TITLE
Port to FireFox?

### ISSUE THREAD

**Issue by HatisEm** [sylouuu/chrome-tab-modifier#46]
Can you port this add-on to FireFox?, I recently changed from Chrome to FireFox because of faster performance but there are no tab modifying add-ons in the FireFox add-on store

**Comment by sylouuu** [comment]
Hi @HatisEm,

Tab Modifier is available for Chrome and Opera as this is the same codebase. Both browsers are sharing the same extension management system.

Firefox is using a "proprietary" solution. You can deal with XUL code and nobody wants to work with as it's a very old system based on XML. It means that I should totally rewrite a new version of Tab Modifier for Firefox. I won't do that. Moreover, Firefox [announced a new future for their extensions system](https://blog.mozilla.org/addons/2015/08/21/the-future-of-developing-firefox-add-ons/). 

Hope this will result in a better future for developing cross-browsers extensions.

Bests

**Comment by HatisEm** [comment]
Thanks for replying, @sylouuu

**Comment by sylouuu** [comment]
A note has been added to the README to link this topic.

Bests

**Comment by olejorgenb** [comment]
Now that firefox is well along its transition to "WebExtensions", maybe this is ripe for reconsideration?

**Comment by sylouuu** [comment]
@olejorgenb I'll reconsider this as soon as the API is stable on every browser. I've done some tests and it's still not consistent. Each browser does not implement everything with the same syntax (or namespace). Like the `chrome` namespace is now `browser` in Firefox but `browser` is not recognized in Chrome.

Wait & see!

**Comment by Happy-Ferret** [comment]
FYI, ``chrome`` is available in Firefox, as well.
I've just tested your add-on and can confirm that the following feature works:

* Rename tab

The others don't quite work, yet.

``Unique tab`` doesn't really work because that's Firefox' new default behavior anyways.

``Mute tab`` I'll have to investigate. Technically, this should work.

**Comment by clfer** [comment]
Hi,

I worked for the few past days on this subject.
Should have commented here earlier but I have a release that seems to work on both browsers. 
You can check my fork here:

https://github.com/clfer/chrome-tab-modifier/tree/firefox/release/0.21.0

**Comment by insign** [comment]
While not ready, I'm using this too much more basic alternative: https://github.com/coolsoft-ita/autopintab

**Comment by atreziout** [comment]
Would someone officially release the firefox port ?
https://github.com/clfer/chrome-tab-modifier/tree/firefox/release/0.21.0

That would be fantastic !

I've tested as temporary add-on in Firefox, it works.

**Comment by Ronef** [comment]
Hi everyone!

Nothing has changed on this issue?

I use both Chrome and FF, and I want this nice extension in FF too 🙂

**Comment by mart-e** [comment]
I see someone has published the extension to firefox:
https://addons.mozilla.org/en-US/firefox/addon/tab_modifier/
seems to be working!

**Comment by olejorgenb** [comment]
@mart-e Nice! Haven't tried it out properly yet, but here are the changes in case anyone is curious: https://gist.github.com/olejorgenb/a6c0a81e52a98a894f7f98a385ebd78b
