### ISSUE TITLE
Adding 

### ISSUE THREAD

**Issue by ChriD** [sylouuu/chrome-tab-modifier#47]
Hi,
First of all this is a great Addon. Thank you for your work!

What do you think of adding some possibility to run a js. script after a page is loaded?
The reason i'd like that is that i like to recolor a element of a site so i know that i am in DEV or PROD 
So in fact i want to change the background of a specific container. eg. Red for PROD and Green for DEV and if there is the posibility to run a script after loading a page that would be great.

**Comment by sylouuu** [comment]
Hi @ChriD, thanks for your feedback!

I'm not sure that the current design fits with this feature.

Configurations are stored in JSON, that means you will get some Javascript inside a JSON-value. And what about the render inside the modal?

This feature is possible I just wonder if it's a good idea and how to adapt the current design.

Bests
