### ISSUE TITLE
Open URL in existing tab

### ISSUE THREAD

**Issue by rmeekers** [sylouuu/chrome-tab-modifier#48]
It would be nice if this extension could support this scenario:

- I have an open (Pinned, Muted, Unique) tab with Gmail
- When I click on a link to a certain email (originating from my todo app for example) it would be nice if it could open that URL in my existing Gmail tab

Now it just closes that tab again.

**Comment by sylouuu** [comment]
Hi,

What do you mean by "I click on a link to a certain email"? Like "mail@domain.com" it opens your GMail so the unique rule is closing that?

Bests

**Comment by rmeekers** [comment]
No, for example a link like this: https://mail.google.com/mail/u/0/#sent/158daf9e96923877
It would be useful if that link could open in my existing tab.

**Comment by sylouuu** [comment]
Hi @rmeekers,

This is fixed in 0.17.4. This version will be available soon.

Best

**Comment by rmeekers** [comment]
great @sylouuu , you made my day :)
