### ISSUE TITLE
Add current site favicon in rules

### ISSUE THREAD

**Issue by dpwrussell** [sylouuu/chrome-tab-modifier#49]
Hi,

I've just been exploring this addon and it's very useful, but there is one place in which I can't use it, but it is desperately needed. Slack tabs are a good example so I will use that. Here is what my tabs look like:

![screen shot 2017-01-04 at 15 37 22](https://cloud.githubusercontent.com/assets/1889043/21658248/c4f146be-d293-11e6-9829-e2519e3bf386.png)

I have 5 different Slack organizations, plus some other stuff. I have asked the Slack devs to add an option to customize the icon on a per org basis, but they have not yet done this, which is what motivated me to try this chrome extension.

The problem is that the favicon is used by slack (and many other web applications also do this) to convey information to the user. In the example above, the first of the slack tabs is alerting me to the fact that I have an unread message mentioning my username specifically. The other four have no unread messages. In the case of slack there are only three options (unread, mentioned and no-unread). The website achieves this by altering the favicon to whatever state is appropriate at the time.

My feature request would be to allow me to match the current favicon in addition to the URL in order to display a different icon for the three different statuses.

**Comment by sylouuu** [comment]
Hi @dpwrussell,

Thanks for your feedback! Much appreciated!

Tell me I understand well: you want to set a custom favicon for each slack organization, that is already possible with Tab Modifier. However you will lose the "notification" with this new favicon.

In that case, as the Slack favicon is drawed on-the-fly, I don't know how to catch this. It would be a very huge work and I'm not sure that it's really doable. If you set another favicon, you have to deal with it.

You may consider the desktop Slack app (Windows or Mac) you will be able to switch quickly between orgs from the sidebar.

Best

**Comment by dpwrussell** [comment]
I would be happy to assign unique icons for url+favicon combinations. e.g. if the url is `https://myorg.slack.or` and the favicon is the one for unread, then I assign a purple circle, or whatever.

Presumably your extension works by monitoring the url and applying a change in icon when certain patterns are matched. I don't know anything about how Chrome extensions work, but it would stand to reason that there would be an event you could register for that would fire whenever a change in favicon would occur which you could then use to reapply the rules.

If the Slack favicon is a canvas, then I think you're probably right in that it isn't really possible to do anything useful with that.

**Comment by sylouuu** [comment]
I have to redirect you to the [Focused scope](https://github.com/sylouuu/chrome-tab-modifier#focused-scope) section.

Tab Modifier is designed to apply a rule when the URL is matched. Unfortunately I can't change the design for few people. I have to think for most of users.

With some time, it's not very hard to fork Tab Modifier and release a clone with extended features.

Hope you'll understand this position.

Best
