### ISSUE TITLE
Locally Stored Favicons

### ISSUE THREAD

**Issue by Zanzacar** [sylouuu/chrome-tab-modifier#5]
I have modified the gmail favicon to have some added initials to differentiate between work/personal. I am using the follow to "attempt" to use a locally store file but it doesn't seem to work. The title changes so I know that works but the icon stays the same.

Do you have any thoughts on this?

```
{
    "twitter.com": {
        "title": "I'm working hard!",
        "icon": "file:///C:/Program%20Files%20(x86)/Google/Chrome/Tab-Modifier/faviconARC.ico"
    }
}
```

**Comment by sylouuu** [comment]
Hi @Zanzacar,

It seems to be a known issue with Chrome. I tried myself and I can reproduce this behavior.

You could find a way to upload your icon somewhere where the file is *displayable*.

Bests

**Comment by sylouuu** [comment]
Quick note to say that this case is listed in the README with few workarounds.
