### ISSUE TITLE
Feature Request: Apply RegEx transformations to existing title

### ISSUE THREAD

**Issue by NeilForsyth** [sylouuu/chrome-tab-modifier#50]
I would like to be able to apply a regex transformation to the existing tab title, instead of completely replacing or adding to it.

e.g. I sign into multiple gmail accounts simultaneously, and each tab is "Inbox (1,234) - address@gmail.com", but when tabs are narrow, all i see is "Inbox (1,234) - ", thus i can't tell which tab is which account. I'd like to switch it around so the mailbox name is first: something like `s/(^.*\)) (.*$)/\2 \1/`

Many other websites start the tab title with some generic phrase followed by more useful title info, it would be great to RegEx capture and omit the generic phrase at the beginning.

Example of two different GMail inboxes, and different eBay pages that look the same:
![tabbar](https://cloud.githubusercontent.com/assets/3574935/21672474/f2494ad8-d376-11e6-881c-932ea77e9b4f.PNG)

**Comment by sylouuu** [comment]
Hi @NeilForsyth,

This feature should work in the current version.

- Create your rule based on GMail like `mail.google.com`
- Enter your Regexp in the "URL matcher" input
- Use `$1` or `$2` inside title to print your variable such as your email

See the [README](https://github.com/sylouuu/chrome-tab-modifier#examples) to get more details about configurations.

Best

**Comment by sylouuu** [comment]
Oh my bad. Yes URL matcher scans the URL with the Regexp, you want to scan the title.

So yes it's not possible.

In case you just want to display your email as a title you try something. Clear URL matcher and put this in the title input : `{.gb_vb} - {title}`

`.gb_vb` seems to be the CSS class where your email is displayed in GMail.

Best

**Comment by NeilForsyth** [comment]
Thanks for that - I've spent some time over the past day figuring out equivalent classes etc. for other sites, and so far it's all working great!

I must say it's more work digging through the DOM than a regex on the title though, so my original feature request still stands, but it's not so critical to me anymore.

...I actually find myself wanting to have a regex (or some other text mangling system) apply from the results of the {selectors}! That's a more powerful request than what I originally asked for, and perhaps a bit much.

Thanks @sylouuu for writing this Chrome extension, and for your support!

**Comment by sylouuu** [comment]
Hello @NeilForsyth,

I've added the "Title matcher" input and it works like the "URL matcher".

The difference is that you have to use `@0` instead of `$0` (dollar syntax reserved to URL matcher) in the title input.

You can combine both to alter your title!

Be sure to opt-in for new version notification in Tab Modifier settings. :)

Let me know after the release if it's OK for you with this new feature!

Best
