### ISSUE TITLE
Can we get support for childnodes somehow?

### ISSUE THREAD

**Issue by ScottBeeson** [sylouuu/chrome-tab-modifier#51]
Please see this SO question for reference: http://stackoverflow.com/questions/41492886/dom-selector-to-get-text-of-element-ignoring-children/41492946?noredirect=1#comment70192261_41492946

Basically I have an element that looks like this:

    <div id="pageTitle">This Page! <a href="nextpage.html">Next Page</a></div>

I want the tab to be named "This Page!" but if I use `{.pageTitle}` it will be named "This Page! Next Page".

**Comment by ScottBeeson** [comment]
p.s. I LOVE this extension.

**Comment by sylouuu** [comment]
Hi @ScottBeeson,

Thanks for your feedback!

You can see the attached commit, this unexpected behavior will be fixed in the next version. Be sure to opt-in for new version notification in Tab Modifier settings. :)

Best
