### ISSUE TITLE
Request: Version Indicator

### ISSUE THREAD

**Issue by ScottBeeson** [sylouuu/chrome-tab-modifier#52]
Could we get a version indicator somewhere in the options interface?  Perhaps near the name?  I made a quick mockup:

![image](https://cloud.githubusercontent.com/assets/108358/21723808/70d0907a-d3f7-11e6-875b-f43440b92284.png)

**Comment by sylouuu** [comment]
Thanks @ScottBeeson. Actually you can know the running version by right-clicking on the extension and select "Manage extensions". You will be redirected to `chrome://extensions/?id=hcbgadmbdkiilgpifjgcakjehmafcjai`.

I think most of users may be confused to see the current version in the Options page.

Best

**Comment by ScottBeeson** [comment]
Fair enough.  Thanks!
