### ISSUE TITLE
Can I use an element attribute as the title?

### ISSUE THREAD

**Issue by ScottBeeson** [sylouuu/chrome-tab-modifier#54]
For instance:

```
<div id="now-playing-media" title="Ed Sheeran - Shape Of You (NOTD Remix)" style="width: 937.703px;">
    <span class="bar-value"><span class="author">Ed Sheeran</span> - Shape Of You (NOTD Remix)</span>
</div>
```

Can I make the tab title "Ed Sheeran - Shape Of You (NOTD Remix)"?

I tried a few things, including `{#now-playing-media:attr("title")}` but can't get anything to work.

**Comment by sylouuu** [comment]
Hello,

Try with `#now-playing-media[title]`. Can't test this week.

Best

**Comment by ScottBeeson** [comment]
Doesn't seem to work.  Tested here: https://plug.dj/tastycat

**Comment by sylouuu** [comment]
Actually it's impossible.

The selector feature works only with node content, but you want to use an attribute value. It's not the same JS method to call.

It will be too much to adapt the code for this edge case.

Best
