### ISSUE TITLE
[Feature Request] Update Title on content change?

### ISSUE THREAD

**Issue by ScottBeeson** [sylouuu/chrome-tab-modifier#55]
I'm trying to use chrome-tab-modifier to display the current track on plug.dj.  It works, but when the song changes the tab title does not update.  This would be a great feature for many sites I believe.

**Comment by sylouuu** [comment]
This will break down your browser performance. Pray for your CPU and memory.

Re-execute the code everytime the page change is not an elegant solution.

Tab Modifier can't add missing features for each website.

Best

**Comment by ScottBeeson** [comment]
You're already using a [MutationObserver](https://hacks.mozilla.org/2012/05/dom-mutationobserver-reacting-to-dom-changes-without-killing-browser-performance/).  What is this for?

        // Set up a new observer
        observer_title = new window.WebKitMutationObserver(function (mutations) {
            if (title_changed_by_me === true) {
                title_changed_by_me = false;
            } else {
                mutations.forEach(function () {
                    if (rule.tab.title !== null) {
                        document.title = processTitle(location.href, document.title);
                    }
                    
                    title_changed_by_me = true;
                });
            }
        });
        
        // Observe when the website has changed the title
        if (document.querySelector('head > title') !== null) {
            observer_title.observe(document.querySelector('head > title'), {
                subtree: true,
                characterresponse: true,
                childList: true
            });
        }

**Comment by sylouuu** [comment]
Sure I already use an observer to detect when the website is changing the title like GMail, Twitter, etc.

I could observe the whole document but trust me it's bad design. This will slow Chrome.

Best
