### ISSUE TITLE
[Feature Request] nth-of-type

### ISSUE THREAD

**Issue by syberlioz** [sylouuu/chrome-tab-modifier#56]
Would it be possible to add an nth-of-type option for DOM element selection?

i.e. {span:nth-of-type(3)}

Thanks!

**Comment by sylouuu** [comment]
Hi,

What's wrong with this? `querySelector` is used to target your node.

Any official selector is supported.

Best

**Comment by ScottBeeson** [comment]
> Would it be possible to add an nth-of-type option for DOM element selection?
>
> i.e. {span:nth-of-type(3)}
>
>Thanks!

I am currently using this exact selector and it works fine:

{.portalTitleInfoVal:nth-of-type(4)}

**Comment by sylouuu** [comment]
Any update @syberlioz?

**Comment by syberlioz** [comment]
My apologies. I didn't have a full understanding of how nth-of-type works as I'm pretty new to the DOM. Thanks for your responses!
