### ISSUE TITLE
Changing the favicon for GitHub doesn't work

### ISSUE THREAD

**Issue by kankaristo** [sylouuu/chrome-tab-modifier#57]
Thanks for a great extension, it's perfect for changing the favicons on pinned tabs, so that it's easier to identify them. Also useful for changing dark favicons to lighter ones, so that they're easier to see on a dark Chrome theme. :+1:

However, changing the favicon doesn't work for GitHub (github.com). Works fine for Slack, Waffle.io, etc.

Changing the tab's title works (so the rule is matched), but the favicon doesn't change.

**Comment by sylouuu** [comment]
Hi @kankaristo,

At the GitHub home page it doesn't work as you described. When I try an external icon like `https://www.google.com/favicon.ico` the console prints:

```
content.js:159 Refused to load the image 'https://www.google.com/favicon.ico' because it violates the following Content Security Policy directive: "img-src 'self' data: assets-cdn.github.com identicons.github.com collector.githubapp.com github-cloud.s3.amazonaws.com *.githubusercontent.com".
```

GitHub contains a CSP that disallows assets loading from unexpected domains. Can't do much about that.

However this CSP doesn't seem to be enabled on all pages. Try just here, on this page.

_Additional note: Preconfigured icons work great even at the GitHub home page._

Best
