### ISSUE TITLE
Long URLs push edit/copy/delete icons off-screen

### ISSUE THREAD

**Issue by augmentedfourth** [sylouuu/chrome-tab-modifier#61]
I'm trying to change the tab title for a very long specific URL, and it works fine. But that long URL now stretches out the "List of Rules" page, and I can't edit/copy/delete any of the rules.

**Comment by sylouuu** [comment]
Hi @augmentedfourth,

Can you provide any screenshot?

Best

**Comment by augmentedfourth** [comment]
<img width="1162" alt="screen shot 2017-01-27 at 2 44 06 pm" src="https://cloud.githubusercontent.com/assets/538363/22390315/2ce38f58-e49f-11e6-8cdf-b92ec1e558e7.png">

**Comment by augmentedfourth** [comment]
An alternate way to fix this for me would be for the extension to look in my bookmarks and rename the tab with the name of the bookmark, so I wouldn't have to make these rules for specific URLs in the settings (this is what I was looking for in the first place, anyway). Should I open that up as a separate feature request?

**Comment by sylouuu** [comment]
As a workaround can you set a shorter URL fragment?

**Comment by augmentedfourth** [comment]
Not really. All parts of the URL are significant, and I could be viewing something with a similar URL but not want it to appear with the same title/icon.

One thing to note, though, is that if I set an icon for this full URL, the bookmark for it changes to the icon I selected in Tab Modifier.

**Comment by sylouuu** [comment]
If there only one part changing in the fragment, just set it and select "Contains" instead of "Starts with".

I won't make a feature related to bookmarks as this is a display issue.

**Comment by augmentedfourth** [comment]
Most of the parts can change, unfortunately (which is why I said "all parts of the URL are significant" before). Do you know of any Chrome extension that works like TabRenamizer in Firefox? That extension uses bookmark names as tab names when any tab with that bookmark URL is open. I'm trying to switch from Firefox to Chrome for performance issues, but it's hard to replicate some of the UI stuff I've gotten used to.

**Comment by sylouuu** [comment]
No sorry I don't know about Firefox universe.

**Comment by sylouuu** [comment]
Fixed in 0.18.2.
