### ISSUE TITLE
PDF link not working

### ISSUE THREAD

**Issue by dzg** [sylouuu/chrome-tab-modifier#62]
Fantastic extension! Thanks!

Any idea why `https://images-na.ssl-images-amazon.com/images/G/01/opt/general/test/KDP_W8BENa._V160201652_.pdf` does not get prefixed?

My rule is match RegExp `.` (for ALL pages) and prefix `aaa {title}`

Is RegExp `.` the best way to match all?

(Also tried match contains `:`)

**Comment by sylouuu** [comment]
Hi @dzg,

Tab Modifier can only change title on an HTML page.

Although the PDF has a tab title, this is not an HTML page. So the Javascript API can't access to the title. Look at [this check](https://github.com/sylouuu/chrome-tab-modifier/blob/release/0.18.2/src/js/content.js#L173).

Best

**Comment by dzg** [comment]
OK, thanks anyway!
