### ISSUE TITLE
Remove extension on Vivaldi - leftover data?

### ISSUE THREAD

**Issue by swedeman** [sylouuu/chrome-tab-modifier#63]
Seem to be having an issue where removing TM from the Vivaldi browser doesn't completely delete all of the previously saved rules.
Would you know if they are being stored in the profile and just not being deleted?
Thank you.

**Comment by sylouuu** [comment]
Hi @swedeman,

How do you know that the browser didn't erase all of data? Can you tell what have you done?

Best

**Comment by swedeman** [comment]
Thank you for the response.

After TM was removed I continued to see tab labels that were ones that had been used when TM was installed. Did clear the cache and history just in case. Vivaldi seems to have its share of short comings even though based on Chrome.

Is there typically a file that may not have been removed in the profile?

 I'm sure its mostly operator error.

**Comment by sylouuu** [comment]
I just:

* installed Vivaldi
* installed Tab Modifier
* created a rule
* refreshed the page to see the rule applied
* uninstalled Tab Modifier
* refreshed the page to see the rule unapplied
* OK

**Comment by swedeman** [comment]
Ok. Thanks for your time.
