### ISSUE TITLE
Tab Modifier is not working consistently

### ISSUE THREAD

**Issue by bottomlineusa** [sylouuu/chrome-tab-modifier#65]
It will change some tabs and not others.  Very inconsistent.  Can this be resolved?  I love this extension, if it would work all the time.

**Comment by sylouuu** [comment]
Hi @bottomlineusa,

Can you provide some examples with your rules please?

Best

**Comment by bottomlineusa** [comment]
Thank you....I have attached a backup of the tab rules I created.
[tab_modifier.zip](https://github.com/sylouuu/chrome-tab-modifier/files/796852/tab_modifier.zip)

**Comment by sylouuu** [comment]
You have specified rules on a private website so I can't analyse what happens...

You are the first to say that the extension "is not working consistently". And Tab Modifier works since many years. You could try other rules on other (popular?) websites to know if it works as expected.

Best

**Comment by bottomlineusa** [comment]
What I did is remove the color icons and it is working fine now.  It may be the call to an outside URL for the icon that this site doesn't like (perhaps as a security measure).    But I love this now that it is renaming the tabs and keeping the name.  It is a huge help to me, and I will show all my clients Tab Modifier.  I think anyone who uses QBO (QuickBooks Online) will get huge time-saving benefit from this.

**Comment by sylouuu** [comment]
Thanks for your feedback @bottomlineusa!

**Comment by sylouuu** [comment]
I reopen your original issue @bottomlineusa.

Are you interested by trying a new Tab Modifier beta version for testing purpose on QBO?

**Comment by bottomlineusa** [comment]
I would love to!

**Comment by sylouuu** [comment]
Go to chrome://extensions/ and enable the "Developer mode".

Disable the current Tab Modifier version (uncheck it).

Click on "Load unpacked extension..." and select the project dist folder you just downloaded (unzip the attached "dist.zip").

[dist.zip](https://github.com/sylouuu/chrome-tab-modifier/files/836078/dist.zip)

Try QBO, all cases can't be supported but I need your feedback! Thanks!

**Comment by sylouuu** [comment]
@bottomlineusa Prefer to answer directly from GitHub not by email. I can't see your answer.

**Comment by sylouuu** [comment]
You have to unzip this file before. Then point on the folder.

Moreover, don't forget to export your rules and reimport them after.

**Comment by bottomlineusa** [comment]
Wow,  I have been using this on 3 company files and so far it is just great!.  The one thing I have to remember (and show others), is that on the memorized reports, QBO uses the memorized report number so I have to make sure to create a special rule for each memorized report per company file, and recognize if I delete the memorized report I will need to recreate or, check my rules.  But that is not a Tab-Modifier issue.   I am loving this version.  So far, I have not run across an issue.    I am using both colors and names.  I don't know if the program will act differently if I remove the colors or don't use them.  I will test that out at some point and let you know if there is an issue there.  But this is just great!  Thank you!   I am excited to show this to my QBO clients!

**Comment by sylouuu** [comment]
Thanks for your report! It should work with/without icons.

Best

**Comment by sylouuu** [comment]
Hope it's still OK, I'll release this new version soon!

**Comment by bottomlineusa** [comment]
Yes,  I was going to ask when this is released so I can get out of developer mode.  I am not seeing any issues with this version.  

Thank you so much!

**Comment by sylouuu** [comment]
You can disable the custom version and enable the official one. The update will be available later today.

**Comment by bottomlineusa** [comment]
I just downloaded  ver 1.8.3.  Thank you.   The one thing you might want to mention in your info page about using Tab Modifier is when you open a Bookmark page that has a rule, it needs to be refreshed before Tab Modifier works.  Not an issue with me.  I just **open and refresh**.  But it might be something someone won't realize, and may think Tab Modifier does not work.  

Thanks for fixing this.  I really appreciate your diligence in getting this to work with QBO (and other log in sites).   Yay!

**Comment by sylouuu** [comment]
I'm sorry but some users reported me that the new version broke some things. Ref https://github.com/sylouuu/chrome-tab-modifier/issues/68

I have to revert my changes until I have more time to work on it.

**Comment by bottomlineusa** [comment]
I understand.   Can you leave me a link to ver 1.8.3 so I can share it with QBO users?  It works great for that.

**Comment by sylouuu** [comment]
Sure.

- Release link: https://github.com/sylouuu/chrome-tab-modifier/releases/tag/0.18.3
- Archive link: https://github.com/sylouuu/chrome-tab-modifier/archive/0.18.3.zip

Unzip and point on the "dist" folder.

**Comment by bottomlineusa** [comment]
Thank you :-)
