### ISSUE TITLE
v0.18.3 Not working if site uses URLrewrite 

### ISSUE THREAD

**Issue by yakunins** [sylouuu/chrome-tab-modifier#68]
Hello. Thanks for great tool!

Sadly, today I uninstallednew verison (0.18.3). Looks like it won't work with websites that uses urlRewrite in its javascript. I have checked on two SPA-like apps. You can try https://login.salesforce.com/

I swithched  back to previous version 0.18.2. Everything is OK there.

**Comment by sylouuu** [comment]
Hi,

Can you tell me what's happening with 0.18.3?

Best

**Comment by yakunins** [comment]
> Can you tell me what's happening with 0.18.3?
1. I noticed your extension won't work on some of my websites.
2. The I checked how it worked on all sites.
3. I noticed on witch websites it fails.

![image](https://cloud.githubusercontent.com/assets/2505676/24098116/b8bd932a-0d8a-11e7-983b-599bacf6def6.png)

**Comment by sylouuu** [comment]
So you are using Tab Modifier only for rewriting icons?

On some websites the default website icon is still used? Is that right?

**Comment by yakunins** [comment]
> using Tab Modifier only for rewriting icons?
I used v0.18.3 features, both change icon and pin tab.

> On some websites the default website icon is still used? Is that right?
Not exactly. On some websites default icon is used and tab wasn't pinned. I guess that means that url-matching do not work well.

**Comment by sylouuu** [comment]
Did you refresh all tabs?

**Comment by yakunins** [comment]
Yes, sure.

**Comment by ThalesH7** [comment]
Hi,

Same thing is happening to me. Is there a way to use v0.18.2 until this is fixed? 

Thank you!

**Comment by ThalesH7** [comment]
I figured out how to install the previous version. Thank you.

**Comment by sylouuu** [comment]
I just pushed a 0.18.4 release that reverts the previous changes. Thanks for your feedback!

**Comment by yakunins** [comment]
Hello! Here is the list of websites on witch I have seen problems:
- https://www.englishclub.com/grammar/adjectives.htm
- https://translate.google.com/ 
- https://go.servicetitan.com/

Hope it helps!

**Comment by sylouuu** [comment]
OK later today you'll get 0.18.5! Thanks!
