### ISSUE TITLE
not working with localhost urls?

### ISSUE THREAD

**Issue by mauricecruz** [sylouuu/chrome-tab-modifier#70]
Thanks for this plugin!

I noticed that my local dev urls aren't being picked up by this plugin anymore. 

Here are my settings:
![image](https://cloud.githubusercontent.com/assets/1640686/24120414/f4bb92e6-0d8a-11e7-86ea-cca750ec4c83.png))

Please let me know if I need to provide any additional information.

**Comment by mauricecruz** [comment]
chrome v 57.0.2987.110. 

Also, noticed an error on my console coming from the plugin. Not quite sure if this is the cause. 

![image](https://cloud.githubusercontent.com/assets/1640686/24123613/9abdc244-0d96-11e7-8f31-b48cc1159369.png)

**Comment by sylouuu** [comment]
I talked about Tab Modifier version, force extensions update you'll get 0.18.4.

**Comment by mauricecruz** [comment]
I reinstalled the extensions and I'm now on ` 0.18.4`. Issue still perists. I think the issue is related to L16 I highlighted above. A type error is thrown and the rest of the code doesn't execute.

![image](https://cloud.githubusercontent.com/assets/1640686/24130267/ee43900c-0dbd-11e7-8f47-e6140e4f2fee.png)

**Comment by sylouuu** [comment]
OK later today you'll get 0.18.5! Thanks!
