### ISSUE TITLE
Rule applying twice?

### ISSUE THREAD

**Issue by vaff** [sylouuu/chrome-tab-modifier#71]
![screen shot 2017-03-21 at 09 49 38](https://cloud.githubusercontent.com/assets/351447/24139272/c7945532-0e1b-11e7-859c-a24dd067a453.png)

Is there a bug or are my rules somehow wrong?

**Comment by sylouuu** [comment]
Hi @vaff you'll get 0.18.5 later today. Tell me if the issue persists.

Thanks!
