### ISSUE TITLE
Would it be possible at all to manually rename a tab?

### ISSUE THREAD

**Issue by ScottBeeson** [sylouuu/chrome-tab-modifier#72]
If I had a resultset open it would be super handy if I could just do a one-off "right-click" and rename.  Is this even possible with a Chrome extension?

**Comment by sylouuu** [comment]
Hi @ScottBeeson,

This is a good idea! I'll take a loot on it.

Best

**Comment by sylouuu** [comment]
You'll receive [0.19.0](https://github.com/sylouuu/chrome-tab-modifier/releases/tag/0.19.0) soon!

**Comment by bottomlineusa** [comment]
Got 0.19.0.  Woo Hoo!  This is great!   Works great with QBO too :-)
