### ISSUE TITLE
Stop working with The Greate Suspender Extension in chrome  57.0.2987.110

### ISSUE THREAD

**Issue by AlexBukh** [sylouuu/chrome-tab-modifier#73]
Stop working with The Greate Suspender Extension in chrome  57.0.2987.110
in ulrs like chrome-extension://klbibkeccnjlkjkiokjodocebajanakg/suspended.html#uri=https://analytics.google.com/analytics/web/?hl=ru&pli=1#report/visitors-overview

**Comment by sylouuu** [comment]
Hello,

I am surprised that it works because an extension can not work in another.

Do you have an error in the Dev Console? What Tab Modifier version are you running?

Best

**Comment by AlexBukh** [comment]
I'm using the latest updates of TM/Chrome. The last Chrome update have brought me profile/history issue, so maybe that is the cause. The second one is The Greate Suspender version: the old works fine on the other system grabbing the TM icons as before. So do not bother, need some testing)

**Comment by AlexBukh** [comment]
It was a broken chrome profile thing. Please, close issue, TM is innosent!)

**Comment by sylouuu** [comment]
Glad to hear that!

Best
