### ISSUE TITLE
installed, not working 

### ISSUE THREAD

**Issue by lake1984** [sylouuu/chrome-tab-modifier#75]
Hi - great idea. I have many tabs open to various sections of a web based CRM. All the tabs only show the name of the CRM, so being able to control the first few characters will be awesome. 

I installed the ext and created my first rule. It does not work. I have tried a few different rules. Does Chrome need to be restarted or any other settings reviewed and tweaked?

**Comment by sylouuu** [comment]
Hi,

You don't need to restart Chrome.

Please go Settings > Export Rules and paste the content here.

**Comment by lake1984** [comment]
{
    "settings": {
        "enable_new_version_notification": false
    },
    "rules": [
        {
            "name": "DS - Daily Appts",
            "detection": "STARTS",
            "url_fragment": "https://my.dealersocket.com/CRM/reports/DailyAppointmentReport",
            "tab": {
                "icon": null,
                "muted": false,
                "pinned": false,
                "protected": false,
                "title": null,
                "title_matcher": null,
                "unique": false,
                "url_matcher": null
            }
        },
        {
            "name": "Test 1",
            "detection": "CONTAINS",
            "url_fragment": "bmamkt",
            "tab": {
                "icon": null,
                "muted": false,
                "pinned": false,
                "protected": false,
                "title": null,
                "title_matcher": null,
                "unique": false,
                "url_matcher": null
            }
        }
    ]
}

**Comment by sylouuu** [comment]
Actually you have set your title in the "name" input instead of the "title" one.

The name is just for you to find your rule among other ones.

So edit your rule and type something in the "title" input.

**Comment by lake1984** [comment]
Ha! That's embarrassing. Working perfectly. Thanks for the quick reply.

**Comment by sylouuu** [comment]
Glad it's OK!

Best
