### ISSUE TITLE
<h1> not extracted on postgresql site.

### ISSUE THREAD

**Issue by spidererrol** [sylouuu/chrome-tab-modifier#78]
### Tab Modifier version

`0.19.2`

### Expected behaviour

Tab to get the name "NOTIFY". (In view-source there is an \<h1\> tag).

### Actual behaviour

Tab gets the name "{h1}"

### Steps to reproduce the behaviour

1. Add the following rule:
  * {"url_fragment":"https://www.postgresql.org/docs/","name":"Useful PostgreSQL Names","tab":{"title":"{h1}","muted":false,"protected":false,"url_matcher":null,"unique":false,"icon":null,"pinned":false}}
2. Visit https://www.postgresql.org/docs/current/static/sql-notify.html

### Work around

I have actually moved to title matching and @1 which works better for me here anyway. But the bug still exists hence the report.

**Comment by sylouuu** [comment]
Hi @spidererrol, thanks for this complete feedback.

Actually, its DOM is really weird so the `h1` is not well detected. Lets see the markup:

```html
<h1><a name="SQL-NOTIFY" id="SQL-NOTIFY"></a>NOTIFY</h1>
```

The anchor is outside the word "NOTIFY", this is the problem. I tried to live-update the DOM to get:

```html
<h1><a name="SQL-NOTIFY" id="SQL-NOTIFY">NOTIFY</a></h1>
```

And it works like a charm. I don't know why they have coded like this. ;)

Best

**Comment by sylouuu** [comment]
Closing this as it's not a TM bug. :)

**Comment by statico** [comment]
Came here for this issue exactly. In case it helps anyone else, here's the title and title matcher I'm using:

![image](https://user-images.githubusercontent.com/137158/33793894-9777ecbe-dc75-11e7-8daf-e301dff9bc47.png)

![image](https://user-images.githubusercontent.com/137158/33793893-901cdad8-dc75-11e7-9c00-bcde4a970a96.png)

Thanks for making this great extension!
