### ISSUE TITLE
Feature requests: Protect tab and unique tab

### ISSUE THREAD

**Issue by irrg** [sylouuu/chrome-tab-modifier#8]
I have two issues with using pinned tabs these days… 1) I keep opening new tabs for some sites and 2) I keep closing my pinned tabs. 

It'd be interesting to see a new feature where there's pinned tab protection… if I try to close a tab, it either asks me if I really want to or just flat out prevents it. 

Second feature would be preventing myself from having my pinned gmail tab open 3 times… i.e. if mail.google.com is opened, it becomes pinned via chrome-tab-modifier and if it already has one of those tabs, it either prevents me from opening another one or tells me to stop being this stupid…

**Comment by sylouuu** [comment]
Hi @irrg,

Thank's for these suggestions.

I'll try to do it when possible.

Bests

**Comment by sylouuu** [comment]
@irrg, just added `protected` property. See README for more info. I'll wait to make `unique` property before creating a new release. You can try it by using the dev version in your Chrome.

**Comment by irrg** [comment]
Awesome! I'm gonna take it for a spin tonight!

**Comment by sylouuu** [comment]
@irrg, I've added `unique` property. I'd like to get a feedback about both. README updated. Tell me if you need some explanations for testing these features without a release.

**Comment by irrg** [comment]
Works great. I think the only thing that's weird now is that unique and protected conflict — example:

I have mail.google.com as a unique, pinned, protected URL. I open another copy of mail.google.com. It becomes pinned, protected, and after that the 'unique' function tries to close it, firing up the 'are you sure you want to leave this page' message. 

I think if you change the order to have 'unique' be handled first, you'll be all set!

**Comment by sylouuu** [comment]
I know. I have to think about it!

**Comment by irrg** [comment]
great work though. Exactly what I had in mind except for the alert!

**Comment by sylouuu** [comment]
@irrg it should be better now!

**Comment by irrg** [comment]
Perfect!
