### ISSUE TITLE
"do you want to leave this site"

### ISSUE THREAD

**Issue by taisau** [sylouuu/chrome-tab-modifier#83]
Extension causes "do you want to leave this site" everywhere.

**Comment by sylouuu** [comment]
You have enabled the "Protected" option on a rule.

Best

**Comment by taisau** [comment]
Thanks!

**Comment by flodi** [comment]
I have the same problem, but why even if I remain on the same site? I'm not closing it (the reason I want protected), I'm just browsing the site. Maybe using Regex instead of Contains in the rule?

**Comment by sylouuu** [comment]
In the browser there is no distinction between leaving a website and refreshing a page (can be the same one or another one).

So the protected feature is only useful on Single Page Applications that does not need to reload the entire page, like GMail.
