### ISSUE TITLE
Rename tab based on Page content

### ISSUE THREAD

**Issue by ASfSDlS61TLT6eoP3Qb7** [sylouuu/chrome-tab-modifier#85]
Chrome Tab modifier is a really great tool, but there is one thing i'm missing. 

I would love to have a feature like create a rule to change the tab name based on the content of the page.

I am a software tester and sometimes I need to login with different user names/roles (for each user a tab). So when I am logged in as 5 different user, it is very confusing which tab is the administrator role. 

The username is in the contents of the page. So it would be great to create a rule that changes the title, based on the contents of the page.

**Comment by sylouuu** [comment]
Hi @ASfSDlS61TLT6eoP3Qb7,

Thanks for your feedback.

This feature already exists. You have to be familiar with HTML selectors. Considering this example markup:

```html
<span class="username">John Doe</span>
```

In your rule, use `{.username}` in the title input.

However, this is possible that the username may be harder to target, depending on the HTML markup.

For live testing your selector before adding it in your rule, go to your page, open Developer Console and try: 

```js
document.querySelector('enter the selector here').childNodes[0].innerText
```

You'll get the value, retry till you fint it. Hope this is clear.

Best

**Comment by ASfSDlS61TLT6eoP3Qb7** [comment]
Oops, well it seems that I didn't put that much time to figure out how it works. I now have it working. And it works great! It now fills out the username in the title automatically! Thanks!!
