### ISSUE TITLE
Can rules stack?

### ISSUE THREAD

**Issue by nfirvine** [sylouuu/chrome-tab-modifier#88]
I.e., I've got rules to:
- JIRA: display the ticket name as the tab title instead of the ticket ID (https://jira/browse/)
- JIRA: change the icon to make it distinguishable from Confluence (https://jira)
- Confluence: change the icon to make it distinguishable from JIRA (https://confluence)

It appears the _change icon_ rule overrides the tab title set by the _display ticket name_ rule. Only the last rule that matches is applied, even if both would match and both would have different effects.

My basic understanding of the code seems to indicate this is true: https://github.com/sylouuu/chrome-tab-modifier/blob/master/src/js/content.js#L12

**Comment by sylouuu** [comment]
Hi @nfirvine thanks for your feedback!

First of all, refer to [this](https://github.com/sylouuu/chrome-tab-modifier#focused-scope).

You can make a rule that does many things, all-in-one. This is an intentional behavior.

Let me know if you have additional questions.

Best

**Comment by nfirvine** [comment]
Ok, fair.

Is there a technical reason why you couldn't do multiple rules and just apply them in order? I might do a PR. Seems like a straightforward change to me, but you know best.

**Comment by sylouuu** [comment]
I understand why some users would like to apply multiple rules for one tab but for most of users, it may be misleading. Indeed you have to deal with rules conflicts. What happens when 2 rules are overwriting the title? I decided to keep the first matched rule to be make it clearer for everyone.

I've also added a way to reorder your rules to let you organize them as the order matters.

Hope you understand my position.

Best

**Comment by nfirvine** [comment]
Yep, I understand your position. Just so you know, I'm not trying to complain; I really like the extension!

To me, the fact that two rules with non-overlapping effects can cancel was counterintuitive. Maybe I'm not a standard user, since I'm used to bizarre rule-based systems like email filters and iptables.

How do you feel about me forking to scratch my own itch?

**Comment by sylouuu** [comment]
Glad you like! Sure up to you to fork and use your custom version since it's MIT. ;)

Yes you are not a standard user!

Best

**Comment by nfirvine** [comment]
Ok, if you're interested in what I did: https://github.com/nfirvine/chrome-tab-modifier/commit/638438e11af532227dd7097202e4dc61eb5ccc8a
