### ISSUE TITLE
DOM content as title not working on a site

### ISSUE THREAD

**Issue by ataiger** [sylouuu/chrome-tab-modifier#89]
### Tab Modifier version

**Browser:** Chrome 59

**Extension version:** 0.19.4

### Expected behavior

Tab title set to '민법'.

### Actual behavior

Tab title set to '{h2}'

### Steps to reproduce the behavior

1. The rule
Detection: Contains
URL fragment: 'law.go.kr'
Title: '{h2}'

2. The site is 'http://law.go.kr/법령/민법'

**Comment by sylouuu** [comment]
@ataiger The given website is using an `iframe` to load its content.

`iframe` are deprecated and TM won't support it.

Best
