### ISSUE TITLE
Self-refreshing Tabs?

### ISSUE THREAD

**Issue by ktonkin** [sylouuu/chrome-tab-modifier#9]
Great extension, thanks. Is there a way to stop tabs from refreshing by themselves (i.e. Twitter home stream), as this changes the tab title back to the unmodified one.

**Comment by sylouuu** [comment]
Hi @ktonkin,

Currently there is no way to prevent page title change by web apps. It's a non-trivial feature.

Bests

**Comment by sylouuu** [comment]
Supported in [0.6.0](https://github.com/sylouuu/chrome-tab-modifier/releases/tag/0.6.0).
