### ISSUE TITLE
Support - Enhancement

### ISSUE THREAD

**Issue by kmugal** [sylouuu/chrome-tab-modifier#90]
Browser: `Chrome` Version 59.0.3071.115 (Official Build) (64-bit)
Extension version: Version: 0.19.4

Hello Syl.

Is it possible to define a list of titles and then randomly choose to rename tab titles from the list for all tabs. 

Khalid.

**Comment by sylouuu** [comment]
Hi @kmugal 

Thank's for your suggestion. I redirect you to the [Focused Scope](https://github.com/sylouuu/chrome-tab-modifier#focused-scope).

Aware of that, you'll understand that I can't implement your suggestion.

Best
