### ISSUE TITLE
[Enhancement Request] Provide tab name via Chrome start-up parameter

### ISSUE THREAD

**Issue by Timofcourse** [sylouuu/chrome-tab-modifier#91]
Hi there-
Is there any chance you'd be able to implement the ability to specify a tab name (or better yet, something that would only preface the original tab name) via Chrome start-up parameter that would apply to all tabs opened in that session?

Thanks for the consideration!

**Comment by sylouuu** [comment]
Hi @Timofcourse 

What do you mean by "via Chrome start-up parameter"?

You can already apply actions on a tab or multiple tabs.

Best

**Comment by Timofcourse** [comment]
For reasons I won't bore you with (unless you're actually curious, in which case I'd be happy to expand upon), we're looking for a way we can control the tab name via command line upon Chrome start up. For example, being able to do something like  "chrome.exe -tab-modifier-name "My Tab {title}" - which in turn would launch Chrome with all tabs prefaced with "My Tab".

Let me know if this makes sense, and if so, if it's something you think can even be accomplished.

Thanks!

**Comment by sylouuu** [comment]
To my knowledge, there is no way to interact with start-up options (or let me know). By the way your need seems to be too specific to start to work on it. With 10k active users, I need to guess if a feature can benefit to many people.

The behavior you describe is already available but the way to achieve it is different. Maybe you need to apply a tab renaming on many computers (maybe in a company with many users) and obviously you don't want to manually set rules on each computer.

Best

**Comment by Timofcourse** [comment]
That's too bad, but I appreciate the response. 

FWIW, we're actually looking for a solution that will allow us to dynamically set the tab title with a variable defined at runtime - not just something statically set the title for all browsers / users. I've yet to find a solution that can accomplish this.

Thanks again.

**Comment by sylouuu** [comment]
OK sorry man, good luck.
