### ISSUE TITLE
Suggestion: Replacement groups for RegExp

### ISSUE THREAD

**Issue by 42degrees** [sylouuu/chrome-tab-modifier#98]
I love this extension, it's great.  The main reason I needed it was for web sites that have tons of "sub-pages" but they all say the same thing.  Amazon AWS is the perfect example.  Currently I have to have a bunch of rules for all of the EC2 pages, like this:
"https:\\/\\/.*\.aws\.amazon\.com\\/ec2.*#Images.*" => EC2 - Images
"https:\\/\\/.*\.aws\.amazon\.com\\/ec2.*#Instances.*" => EC2 - Instances
"https:\\/\\/.*\.aws\.amazon\.com\\/ec2.*#LoadBalancers.*", => EC2 - Load Balancers
"https:\\/\\/.*\.aws\.amazon\.com\\/ec2.*#SecurityGroups.*" => EC2 - Security Groups

But it would be cool to be able to do this:
"https:\\/\\/.*\.aws\.amazon\.com\\/([^/]+).*#([^:]+).*" => $1 - $2

This would produce titles that are good enough (the titles wouldn't have spaces, but it's livable).  

Thanks again.

**Comment by sylouuu** [comment]
Hi @42degrees,

Thanks for your feedback, much appreciated.

I'm not very comfortable with RegExp but variables are already supported. Check out [few examples](https://github.com/sylouuu/chrome-tab-modifier#examples). In addition, refer to [this snippet](https://github.com/sylouuu/chrome-tab-modifier/blob/release/0.20.0/src/js/content.js#L137).

Best

**Comment by 42degrees** [comment]
Thanks for the quick response, I did not see that in the examples.  It might be worth putting a small blurb on the edit dialog to that effect.  

The feature does not appear to be working as I created the following rule:
{
            "name": "AWS URLs",
            "detection": "REGEXP",
            "url_fragment": "https:\\/\\/.*\\.aws\\.amazon\\.com\\/([^\\/]+)\\/.+#([^:]+).*",
            "tab": {
                "icon": null,
                "muted": false,
                "pinned": false,
                "protected": false,
                "title": "$1 - $2 {a#nav-usernameMenu > div.nav-elt-label}",
                "title_matcher": null,
                "unique": false,
                "url_matcher": null
            }
        }

The title that I see in the browser is: "$1 - $2 sgartner @ xyz"

I tried putting in @0 and $0 as well, just to see what I get and both of these produced @0 and $0 unchanged.  I'll pull the code and see if I can figure out why it's broken (I have been using regular expressions for 30 years, they rock!).

**Comment by 42degrees** [comment]
OK, after going through the code, I completely misunderstood the Regular Expression variable feature.  I thought that just setting the "URL Fragment" to RegExp and putting grouping into that caused the $x replacements to work.  I hadn't even noticed the two fields at the bottom of the configuration dialog (Title Matcher and URL Matcher).  Now I get what you were going for!

Now that I understand (and a whole unnecessary fork later ;-) it's working great!

Thanks!

**Comment by sylouuu** [comment]
Glad it's OK for you now! I'm aware of this (hidden fields if you don't scroll).

Best
