### ISSUE TITLE
processPage chooses the last item that matches rather than the first

### ISSUE THREAD

**Issue by 42degrees** [sylouuu/chrome-tab-modifier#99]
_In case of bug report, please fill this template and remove italic lines_
_Otherwise, clear all and type :)_

### Tab Modifier version

**Browser:** `Chrome` or `Opera`
Chrome
**Extension version:** `X.Y.Z`
0.20.0
_Can be found here: chrome://extensions/?id=hcbgadmbdkiilgpifjgcakjehmafcjai_
chrome-extension://hcbgadmbdkiilgpifjgcakjehmafcjai
### Expected behavior

_What do you expect?_
Pick the first matching rule
### Actual behavior

_What actually happen?_
It picks the last matching rule.
### Steps to reproduce the behavior

_Please describe the steps to help me to reproduce the actual behavior_

In content.js, processPage(), it is looping over tab_modifier.rules and no matter how many rules it finds that match the current URL, it keeps searching.  It sets and then overwrites "rule" many times until it exhausts the list.

Instead, I recommend you exit the loop as soon as "rule" has been set to a value.  This will be less wasteful (running every rule on every page) and is more intuitive (first come, first serve).  The way it's coded now it can be really hard to guess which rule it will pick as the first rule and the 17th out of 30 match and it will take the 17th rule.

Here's how I changed the code on my local:

```
rule = null;
for (var i = 0; i < tab_modifier.rules.length; i++) {
    // If we found a matching rule, we don't need to continue
    if (rule !== null)
        break;
    
    /* testing all the rules here */
}
```

Thanks for a cool extension!

Scott

**Comment by sylouuu** [comment]
Thanks Scott for the report. No ETA for this fix yet.

Best

**Comment by sylouuu** [comment]
@42degrees It seems to be already included.

See: https://github.com/sylouuu/chrome-tab-modifier/blob/release/0.20.0/src/js/content.js#L15

There is a `break` after any assignation to `rule`. Can you please test with the 2 same URL fragment with different options and tell me if the first one is taken? It's OK for me.

Best

**Comment by sylouuu** [comment]
Closing, don't hesitate to contact me if you encounter this behavior.

Best
